/*
Navicat MySQL Data Transfer

Source Server         : Wongsir
Source Server Version : 50051
Source Host           : localhost:3306
Source Database       : advancesearch

Target Server Type    : MYSQL
Target Server Version : 50051
File Encoding         : 65001

Date: 2017-03-25 16:21:49
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for keyword
-- ----------------------------
DROP TABLE IF EXISTS `keyword`;
CREATE TABLE `keyword` (
  `id` int(11) NOT NULL auto_increment,
  `keyWord` varchar(128) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of keyword
-- ----------------------------
INSERT INTO `keyword` VALUES ('1', '中国');
INSERT INTO `keyword` VALUES ('2', '陈晓猛');
INSERT INTO `keyword` VALUES ('3', '华南农业大学');

-- ----------------------------
-- Table structure for searchitem
-- ----------------------------
DROP TABLE IF EXISTS `searchitem`;
CREATE TABLE `searchitem` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(128) NOT NULL,
  `content` varchar(2048) default NULL,
  `url` varchar(1024) NOT NULL,
  `searchKey` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=288 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of searchitem
-- ----------------------------
INSERT INTO `searchitem` VALUES ('1', '中国吧_百度贴吧', '贴吧，全球最大中文社区。中国吧，目录：其他地区及话题，有750807个吧友关注，共发布23127404条贴子。来这儿结识和你志同道合的朋友吧！', 'http://tieba.baidu.com/f?kw=%D6%D0%B9%FA', '中国');
INSERT INTO `searchitem` VALUES ('2', '中国·广州', '“中国广州”网(www.guangzhou.gov.cn或www.gz-gov.org)由中共广州市委宣传部主办和主管的全面反映广州政治、经济、文化和历史的官方权威网站，包括“网上广州”和“网上宣传 ...', 'http://www.guangzhou.gov.cn/', '中国');
INSERT INTO `searchitem` VALUES ('3', '中国政府网_中央人民政府门户网站', '中国政府网由国务院办公厅主办，中国政府网运行中心负责运行维护,是国务院和国务院各部门，以及各省、自治区、直辖市人民政府在国际互联网上发布政府信息和提供 ...', 'http://www.gov.cn/', '中国');
INSERT INTO `searchitem` VALUES ('4', '中国银行全球门户网站', '中国银行是中国国际化和多元化程度最高的银行，在中国内地、香港、澳门、台湾及37个国家为客户提供全面的金融服务。主要经营商业银行业务，并通过附属机构 ...', 'http://www.boc.cn/', '中国');
INSERT INTO `searchitem` VALUES ('5', '百度一下，你就知道', '百度一下，你就知道 ... 手机百度', 'http://www.baidu.com/', '中国');
INSERT INTO `searchitem` VALUES ('6', '国内新闻_环球网', '环球网国内新闻着力于报道国内最新要闻、时事新闻、海外看中国、国内各地动态、港澳新闻、政策观察与解读、深度报道、新闻图片、新闻人物等中国新闻。通过梳理 ...', 'http://china.huanqiu.com/', '中国');
INSERT INTO `searchitem` VALUES ('7', '中国_环球万国_环球网', '中国（6张） “中国”又以“中华”、“华夏”、“神州”等代称出现，最早指“天下的中心”，即黄河中下游的中原河洛地带，后逐渐含有王朝统治的正统性含义。', 'http://country.huanqiu.com/china', '中国');
INSERT INTO `searchitem` VALUES ('8', '中国银行', '中国 银行股份有限公司 版权所有 操作提示 操作失败! ...', 'https://ebsnew.boc.cn/boc15/login.html', '中国');
INSERT INTO `searchitem` VALUES ('9', '军事_中国网_权威军事新闻网站', '中国网军事频道是中国最权威的军事网站之一，报道中国、国际等全球军事新闻。主要有以下栏目：军方发布、中国军事、国际军事、军情24小时、武器库、论战、军史 ...', 'http://military.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('10', '中国银行', '中国 银行股份有限公司 版权所有 操作提示 操作失败! ...', 'https://ebsnew.boc.cn/boc15/login.html', '中国');
INSERT INTO `searchitem` VALUES ('11', 'Google', 'google.com.hk 请收藏我们的网址', 'http://www.google.cn/', '中国');
INSERT INTO `searchitem` VALUES ('12', 'Apple (中国) - 官方网站', '率先一睹 MacBook Pro、iPhone 7 和 Airpods，以及 iPad、Apple Watch、iOS、watchOS、macOS 等。访问网站以进一步了解。 ... 天生一对。来自 Apple 的精彩配 …', 'http://www.apple.com/cn/', '中国');
INSERT INTO `searchitem` VALUES ('13', '中国银行全球门户网站', '中国银行是中国国际化和多元化程度最高的银行，在中国内地、香港、澳门、台湾及37个国家为客户提供全面的金融服务。主要经营商业银行业务，并通过附属机构 ...', 'http://www.boc.cn/index.html', '中国');
INSERT INTO `searchitem` VALUES ('14', '中国知网', '中国知网知识发现网络平台—面向海内外读者提供中国学术文献、外文文献、学位论文、报纸、会议、年鉴、工具书等各类资源统一检索、统一导航、在线阅读和 ...', 'http://www.cnki.net/', '中国');
INSERT INTO `searchitem` VALUES ('15', '中国上海', '“中国上海”是在上海市委、市政府领导亲自关心、指导下建立和发展起来的政府门户网站，始终坚持以努力建设“服务政府、责任政府、法治政府”为目标，以“为民 ...', 'http://www.shanghai.gov.cn/', '中国');
INSERT INTO `searchitem` VALUES ('16', '189邮箱', '中国电信网上营业厅，为电信客户提供充值交费、费用查询、业务办理、在线客服、故障申告、投诉咨询及品牌专区等全方位的电子自助服务；中国电信——世界触手可及。', 'http://www.189.cn/', '中国');
INSERT INTO `searchitem` VALUES ('17', '国务院_中国政府网', '中国政府网国务院主栏目发布国务院领导（总理、副总理、国务委员及秘书长）的会议、活动、讲话、出访等信息；发布国务院常务会议和国务院全体会以及 ...', 'http://www.gov.cn/guowuyuan/', '中国');
INSERT INTO `searchitem` VALUES ('18', '佳能（中国）', '佳能公司是以光学为核心的相机与办公设备制造商，始终以创造世界一流产品为目标，积极推动事业向多元化和全球化发展。', 'http://www.canon.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('19', 'iPad - Apple (中国)', '探索 iPad 的精彩世界。了解现有两款尺寸的 iPad Pro，以及 iPad Air 2 和 iPad mini 的种种精彩。访问 Apple 网站来进一步了解、购买产品，以及获得技术支持。', 'http://www.apple.com/cn/ipad/', '中国');
INSERT INTO `searchitem` VALUES ('20', '军事_中国网_权威军事新闻网站', '中国网军事频道是中国最权威的军事网站之一，报道中国、国际等全球军事新闻。主要有以下栏目：军方发布、中国军事、国际军事、军情24小时、武器库、论战、军史 ...', 'http://military.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('21', 'NBA中国官方网站', '©2015年著作权 NBA 中国 所有权保留。 NBA.com/China上除去使用条款中所特别提及的部分之外，其它任何内容都不得以任何形式被复制、再传播，或篡改。 进入 ...', 'http://china.nba.com/', '中国');
INSERT INTO `searchitem` VALUES ('22', '中国邮政速递物流', '版权所有：中国邮政速递物流 [京ICP证030621号] 京公网安备[110401400184] 扫描二维码关注 EMS微信自助平台！ ...', 'http://www.ems.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('23', '军事－中华网－中国最大的军事网站', '中国海军多机型机群出宫古海峡赴西太实兵对抗演练 中国空间站核心舱明年发射 可硬扛小于10cm太空碎片 金正男案朝鲜嫌犯将被驱逐 朝鲜声明金死于心脏病', 'http://military.china.com/', '中国');
INSERT INTO `searchitem` VALUES ('24', '佳能（中国）', '佳能公司是以光学为核心的相机与办公设备制造商，始终以创造世界一流产品为目标，积极推动事业向多元化和全球化发展。', 'http://www.canon.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('25', '惠普中国 | 惠普中国 - HP® Official Site | Laptop …', '惠普中国 | 计算机，笔记本电脑，打印机，更多 开学啦！新学期换本行动 立即选购 开学有礼，返校优惠嗨不停！丰富礼品，专属优惠, 新装备助跑新学期 ...', 'http://www8.hp.com/cn/zh/home.html', '中国');
INSERT INTO `searchitem` VALUES ('26', '中国旅游攻略_中国自由行/自助游攻略_中国游记攻略指南 ...', '中国旅游攻略，穷游网为旅行者提供中国旅游交通、签证、货币、地图、注意事项，分享中国旅游景点、美食、购物、线路、酒店等实用信息，为穷游er制订中国 ...', 'http://place.qyer.com/china/', '中国');
INSERT INTO `searchitem` VALUES ('27', '欢迎访问中国建设银行网站', '中国建设银行，在全球范围内为台湾、香港、美国、澳大利亚等国家或地区提供全面金融服务，主要经营公司银行业务、个人银行业务和资金业务，包括居民储蓄存款 ...', 'http://ccb.com/cn/home/index.html', '中国');
INSERT INTO `searchitem` VALUES ('28', 'HTC 中国', '中国 国家/ 地区 Australia Österreich Bangladesh Brazil Canada - English Canada - Français Česká republika 中国 Danmark Deutschland España Suomi France Hong …', 'http://www.htc.com/cn/', '中国');
INSERT INTO `searchitem` VALUES ('29', '财经中心_中国网', '凡本网站注明“来源：中国网财经”的所有作品，均为本网合法拥有版权或有权使用的作品，未经本网授权不得转载、摘编或利用其它方式使用上述作品。', 'http://finance.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('30', '惠普中国 | 惠普中国 - HP® Official Site | Laptop …', '惠普中国 | 计算机，笔记本电脑，打印机，更多 开学啦！新学期换本行动 立即选购 开学有礼，返校优惠嗨不停！丰富礼品，专属优惠, 新装备助跑新学期 ...', 'http://www8.hp.com/cn/zh/home.html', '中国');
INSERT INTO `searchitem` VALUES ('31', '中国农业银行', '中国农业银行总行网络金融部2017年社会... 2017-02-28 便捷服务 掌上银行下载 行情数据 图说农行 营业机构查询 在线预约排队 信用卡申请 自助客服 WAP网银 ...', 'http://www.abchina.com/cn/', '中国');
INSERT INTO `searchitem` VALUES ('32', '视频中国_中国网', '总编辑带来的国际评论，老外们打造的热点分析，快嘴们的经济圆桌，有深度的人文记录，网络间的趣事分享，共同组成的中国三分钟微视频专区。', 'http://v.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('33', '军事_中国网_权威军事新闻网站', '中国网军事频道是中国最权威的军事网站之一，报道中国、国际等全球军事新闻。主要有以下栏目：军方发布、中国军事、国际军事、军情24小时、武器库、论战、军史 ...', 'http://military.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('34', '手机中国——专业、有态度的手机门户', '手机中国是一个实现了专业、时尚、品位并重的新兴手机媒体。相对于传统手机媒体不同之处在于，手机中国不仅提供指导消费、倡导应用，同时还在引领着手机的时尚与 ...', 'http://www.cnmo.com/', '中国');
INSERT INTO `searchitem` VALUES ('35', 'China.org.cn - China news, weather, business, travel ...', 'China\'s sports and culture authorities will regulate the phenomenon of open-air fitness dancing 广场舞), which is known for generating widespread public complaints about) ...', 'http://www.china.org.cn/', '中国');
INSERT INTO `searchitem` VALUES ('36', 'Microsoft – 官方网站', '微软中国下载中心 所有 Windows 下载 Windows 10 Apps Office Apps Microsoft Lumia Apps Internet Explorer 价值观 教育 公司 公司新闻 中文(中华人民共和国 与我们 ...', 'http://www.microsoft.com/zh-cn', '中国');
INSERT INTO `searchitem` VALUES ('37', '军事－中华网－中国最大的军事网站', '叙部长:西方要参与叙利亚重建先道歉 中国有优先权 媒体解局:究竟是谁杀死了金正男? 马来西亚警方：朝鲜使馆要求交出金正男遗体 破纪录！中国自主打造世界最 ...', 'http://military.china.com/zh_cn/', '中国');
INSERT INTO `searchitem` VALUES ('38', 'BMW 中国', 'BMW 中国 企业社会贡献 概述 推动社会发展 安全出行与可持续发展 宝马爱心基金 企业社会贡献荣誉奖项 报告下载 BMW Next 100 概述 The BMW VISION NEXT 100 ...', 'http://www.bmw.com.cn/zh/index.html', '中国');
INSERT INTO `searchitem` VALUES ('39', '中国政府网', '中国位于亚洲东部，太平洋西岸。陆地面积约960万平方千米，东部和南部大陆海岸线1.8万多千米，内海和边海的水域面积约470多万平方千米。海域分布有大小岛屿7600多个 ...', 'http://www.gov.cn/test/2005-08/11/content_27116.htm', '中国');
INSERT INTO `searchitem` VALUES ('40', 'BMW 中国', 'BMW 中国 企业社会贡献 概述 推动社会发展 安全出行与可持续发展 宝马爱心基金 企业社会贡献荣誉奖项 报告下载 BMW Next 100 概述 The BMW VISION NEXT 100 ...', 'http://www.bmw.com.cn/zh/index.html', '中国');
INSERT INTO `searchitem` VALUES ('41', '图片中国_中国网', '图片中国是中国网旗下的大型多媒体图片外宣平台，汇集优秀摄影师及图片编辑，第一时间提供优质图片新闻，眼观中国内外，见证中国发展过程中的重要时刻与瞬间。', 'http://photo.china.com.cn/index.htm', '中国');
INSERT INTO `searchitem` VALUES ('42', 'Dell - 戴尔官方网站 | Dell 中国大陆', '欢迎访问戴尔官方网站。Dell中国为个人、家庭、企业办公等提供高品质戴尔产品及服务。登录Dell官方网站查询最新Dell产品价格、戴尔优惠活动、戴尔售后服务信息等。', 'http://dell.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('43', 'Microsoft – 官方网站', '微软中国下载中心 所有 Windows 下载 Windows 10 Apps Office Apps Microsoft Lumia Apps Internet Explorer 价值观 教育 公司 公司新闻 中文(中华人民共和国 与我们 ...', 'http://www.microsoft.com/zh-cn', '中国');
INSERT INTO `searchitem` VALUES ('44', '欢迎访问中国建设银行网站', '中国建设银行，在全球范围内为台湾、香港、美国、澳大利亚等国家或地区提供全面金融服务，主要经营公司银行业务、个人银行业务和资金业务，包括居民储蓄 ...', 'http://ccb.com/portal/cn/home/index.html', '中国');
INSERT INTO `searchitem` VALUES ('45', '财经中心_中国网', '凡本网站注明“来源：中国网财经”的所有作品，均为本网合法拥有版权或有权使用的作品，未经本网授权不得转载、摘编或利用其它方式使用上述作品。', 'http://finance.china.com.cn/', '中国');
INSERT INTO `searchitem` VALUES ('46', '银行-HSBC | 汇丰银行（中国）', '汇丰银行(中国)-HSBC Bank(China),是香港上海汇丰银行有限公司全资拥有的外商独资银行.汇丰(中国)为客户提供卓越的个人银行理财业务和优质的工商企业金融 ...', 'http://www.hsbc.com.cn/1/2/', '中国');
INSERT INTO `searchitem` VALUES ('47', '中国传媒大学 白杨网', '中国传媒大学白杨网（简称“白杨网”）是代表中国传媒大学的唯一官方网站，是教育部高校校园网络文化建设首批试点单位建设成果，还是中国传媒大学校内教学实践 ...', 'http://www.cuc.edu.cn/', '中国');
INSERT INTO `searchitem` VALUES ('48', 'Home - 中文 - China', '西门子的解决方案正在支持中国转型升级。西门子将电气化、自动化、数字化的力量融入各行各业，以前所未见的高度、速度、精度和深度，让关键所在，逐一实现。', 'http://www.siemens.com/cn/zh/home.html', '中国');
INSERT INTO `searchitem` VALUES ('49', '中国.芜湖', '“中国•芜湖”芜湖市政府网站，由芜湖市人民政府办公室主办，芜湖市政务公开办公室承办，是芜湖市政府在互联网上公开各类政务信息、推行政务公开、提供 ...', 'http://www.wuhu.gov.cn/', '中国');
INSERT INTO `searchitem` VALUES ('50', '中国 - 搜狗百科', '外文名：People\'s Republic of China（缩写P.R.C.）', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJg6SgaQeoWR5lIGdKcPpc2hNa2iAQb6VDlRETeZ66qVHsYcvmgZQKFkQ..&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('51', '佳能（中国）', '体验会 EOS 5D Mark IV新登场 佳能（中国）官方网上商城 办公类产品及解决方案 工业类产品及解决方案 京ICP备05038060号 佳能公司是以光学为核心的相机与办公设备制造商，始终以创造世界一流产品为目标，积极推动事业向多元化和全球化发展。', 'http://www.sogou.com/link?url=DSOYnZeCC_qGTq2SbE85gydQRoztLvNXreaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('52', '中国政府网_中央人民政府门户网站', '中国政府网由国务院办公厅主办，中国政府网运行中心负责运行维护，是国务院和国务院各部门，以及各省、自治区、直辖市人民政府在国际互联网上发布政府信息和提供在线服务的综合平台，第一时间权威发布国务院重大决策部署和重要政策文件，国务院领导同志重要...', 'http://www.sogou.com/link?url=DSOYnZeCC_qetJvTgG4EhsXCztk0J-wH&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('53', '本田中国', '欢迎访问Honda本田中国官方网站。本站提供关于本田产品、先进技术的介绍，和公司在国内及全球范围社会活动的最新资讯。 2017.02.27 Honda发布2017年赛车运动参赛计划 2017.02.08 Honda中国发布2017年1月终端汽车销量 2017.02.07 日立汽车系统及Honda就成立...', 'http://www.sogou.com/link?url=DSOYnZeCC_o0gzy6Dl-4NSdQRoztLvNXreaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('54', '中国的最新相关信息', '《匠心》张国立联手龚琳娜夫妇奏响中国声音|龚琳...', 'http://www.sogou.com/link?url=6IqLFeTuIygMXRZ15ROdAJMgcJCbcPmKl0deZNrfKQ3hI71xeSyviLddI5f-gfXvFRXcJiKUWJvZ8osNcp4GnBzwSvJ80lQZ4CsGBxED4GE.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('55', '欢迎来到中国合肥门户网站', '1982年8月参加工作，1985年12月加入中国共产党，中央党校研究生学历， 经济学学士... 合肥市人民政府主办，合肥市政府对外信息发布窗口，合肥地方综合性网站。', 'http://www.sogou.com/link?url=DSOYnZeCC_ogsE_4c4pS0mQJ6AJM-tu1reaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('56', '中国·邢台', '|专题专栏站内检索： ·邢台新闻联播 ·行风热线·走遍中国邢台 ·魅力邢台市委召开县... 含政务公告、新闻、办事指南，市政府网站。', 'http://www.sogou.com/link?url=DSOYnZeCC_op9ZMPd_HmlF-6RZ8aDQf4xcLO2TQn7Ac.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('57', '中国网--网上中国', '国家重点新闻网站，拥有十个语种独立新闻采编、报道和发布权；第一时间报道国家重大新闻事件；国情信息库服务全球读者了解中国；国务院新闻办公室发布会独家网络直播发布网站；拥有国内外顶级学者专家资源，独家编发各种相关政策解读。', 'http://www.sogou.com/link?url=DSOYnZeCC_rz88Xns-EirCdQRoztLvNXreaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('58', 'Sony China Portal 首页 - 索尼（Sony）中国网站', '索尼（Sony）在中国网站，全面介绍Sony公司的各项业务.提供丰富的产品信息，包括数码相机，摄像机，笔记本电脑，电视系列，影音产品等以及售后服务和购买服务', 'http://www.sogou.com/link?url=DSOYnZeCC_qMA4T-xCU8xfo8k9PSv4Fv&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('59', '中华人民共和国教育部政府门户网站', '中华人民共和国教育部网站。教育部是主管教育事业和语言文字工作的国务院组成部门。含机构设置、教育新闻、政策法规、公报公告、行政审批、项目指南、招生考试、文献资料、在线服务、教育问答等内容。', 'http://www.sogou.com/link?url=DSOYnZeCC_rLeEdbJ8z_pmy70yUaL4Tl&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('60', '中华人民共和国国防部', '主要发布中国国防和军队建设权威信息，旨在对外传递中国军方声音，宣传中国国防政策，加强与外军交流合作，展示中国军队良好形象，促进国防和军队现代化建设。', 'http://www.sogou.com/link?url=DSOYnZeCC_o1KYKyODKOj1v-_as2MUne&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('61', '中国移动官方网站', '中国移动官方网站为您提供业务介绍，手机话费充值查询，套餐资费介绍及网上查询办理，号码购买，优惠购机，积分查询，优惠活动等网上自助服务。', 'http://www.sogou.com/link?url=DSOYnZeCC_oPssWwI4KPkFE36avUO9cQ&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('62', '中国教育在线 - 中国最大的教育门户网站', '中国教育在线是中国最大的综合教育门户，主要发布高考、考研、自考、成人高考、教师招聘、就业、留学等权威的招考、招生、就业、招聘、复习、辅导信息，并设有校园、博客、外语、公务员、在职硕士、民校、考试书店等栏目。', 'http://www.sogou.com/link?url=DSOYnZeCC_rrVBaFidxbmMXCztk0J-wH&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('63', '中证网-中国最权威的证券财经资讯网站', '中证网-中国最权威的财经证券资讯网站，为您全方位提供证券财经资讯及全球金融市场行情，覆盖证券、股票、基金、期货、产权、保险、银行、博客、股吧等财经综合信息；', 'http://www.sogou.com/link?url=DSOYnZeCC_p-PX8Dy2x-wrdGEV_50fMb&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('64', '中国_知乎', '用户签名: 我就是我,何须改变,雄风依旧 最近回答问题: 中国南海的现状怎么样?中美之间战争是否不可避免?', 'http://www.sogou.com/link?url=DSOYnZeCC_qbIE3Bv5WAGNCNb5y3NB1YdoXAmIJpc7IiF6t0LB8PsK3mlRzfPLR2&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('65', '中华人民共和国农业部', '具备新闻宣传、政务公开、网上办事、公众互动和综合信息服务功能，目前日均点击数600万次左右，成为具有权威性和广泛影响的中国国家农业综合门户网站。网站由中华人民共...', 'http://www.sogou.com/link?url=DSOYnZeCC_o8BRvOvoBH7Fv-_as2MUne&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('66', '中国书法网|中国书法网|中国书法门户网站', '中国书法网 最后发表： 2017-2-12 17:27 ≡ 书法篆刻交流区 ≡ 2010年4月经典竞临-------汉隶《 ... 中国书协会员许凯军篆刻_2016 ≡ 学术交流区 ≡ 别让书法评论进入“死”评的怪圈 小...', 'http://www.sogou.com/link?url=DSOYnZeCC_qzh12QTNZUYSszUlHzhbb1reaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('67', '中华人民共和国司法部', '中华人民共和国司法部主办，提供部门机构设置、职责和动态、政务公告等信息。 中央纪委驻司法部纪检组 司法研究所（研究室） 中国司法行政戒毒工作协会 司法鉴定科学技术研...', 'http://www.sogou.com/link?url=DSOYnZeCC_oZEebTAHaOBVv-_as2MUne&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('68', '中国经济网——国家经济门户', '中国经济网是国家重点新闻网站中唯一以经济报道为中心的综合新闻网站，每日采写大量经济新闻，同时整合国内主要媒体经济新闻及信息，为政府部门、企业决策提供权威的参考依据；为所有关注经济生活的网络读者提供丰富及时的经济新闻。', 'http://www.sogou.com/link?url=DSOYnZeCC_q1n7CNRFvLhm4YafSeot-j&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('69', '中国研究生招生信息网', '中国研究生招生信息网是隶属于教育部的以考研为主题的官方网站，是教育部唯一指定的研究生招生考试网上报名及调剂网站，主要提供研究生网上报名及调剂、专业目录查询、在线咨询、院校信息、报考指南和考试辅导等多方面的服务和信息指导。', 'http://www.sogou.com/link?url=TdXYaTdl0k6VCR8qiH2c6EOoWMJdhXxP&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('70', '中国电信集团公司 CHINA TELECOM', '中国电信集团公司官方网站，中国电信互联网门户，发布中国电信官方权威信息；为电信客户提供充值交费、费用查询、业务办理、在线客服、故障申告、投诉咨询及品牌专区等全方位的电子自助服务；中国电信——世界触手可及。', 'http://www.sogou.com/link?url=DSOYnZeCC_rz88Xns-EirJDX3L_VDx82-jyT09K_gW8.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('71', '中国教育考试网', '主办单位：中华人民共和国教育部考试中心，全国高等教育自学考试委员会办公室。是全国考试办公室为广大考生提供求学咨询、招考指南、网上报考等全方位服务的大型招生考试...', 'http://www.sogou.com/link?url=DSOYnZeCC_qR71qKilLp1T4IRDdG1RpI&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('72', '中国建材网-中国最好的建材行业门户网站', '中国建材网作为中国最好的建材行业门户网站，主要提供建材价格、建材行业市场分析、各科建筑材料知识、建材招商、中国建材最新资讯、建材五金行情报道、建材品牌选购、中国建材公司、中国新型建材材料等丰富内容信息，更多信息可登陆中国建材网（www.bmlink...', 'http://www.sogou.com/link?url=DSOYnZeCC_oRaShgCBHRspnvC8KPpJ6x&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('73', '中华人民共和国国家工商行政管理总局', '工商总局关于加强互联网领域消费者权益保护工作的意见 中国人民银行 工商总局关于个体工商户“两证整合”登记制度改革涉... 关于... 国家工商行政管理总局主办，组织监督市场交易行为，组织监督流通领域商品质量，组织查处假冒伪劣等违法行为，保护经营者、消费者...', 'http://www.sogou.com/link?url=DSOYnZeCC_qqSI6X3hfqtyJ667Hf7_oz&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('74', '中国采购与招标网_官网_中国最大的招标采购信息服务平台', '准！快！全！就上中国采购与招标网！16年行业积累，中国采购与招标网涵盖所有领域招投标、拟建项目信息，日更新20000余条，是业内最权威、最信赖的资讯交易门户。', 'http://www.sogou.com/link?url=DSOYnZeCC_rz88Xns-EirAPMlKwk6uHZ-jyT09K_gW8.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('75', '投资中国网 - 中国股权投资行业第一门户网站', '红杉资本 经纬中国 张颖 深度 创业公司的信息安全分为两部分：内部安全和外部安全。 瓜子二手车 车坚定 查博士 投融动态 全部 专访 全部 专题：ofo完成D轮融资 人物 对于腾讯来...', 'http://www.sogou.com/link?url=DSOYnZeCC_rz88Xns-EirPfRBVEW6c9O-jyT09K_gW8.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('76', '中国篮协官方网站 >> 首页', '包括CBA完全资料及技术统计资料，官方声音，CBA赛事、WCBA赛事、历史数据查询、资料库、竞赛计划、中国篮球学校、中国篮球城市、裁判园地、球迷论坛等内容。提供男...', 'http://www.sogou.com/link?url=DSOYnZeCC_r9EctEI2-dclv-_as2MUne&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('77', '欢迎您访问中国注册会计师协会网站！', '主要职责：办理注册会计师注册；拟订行业准则、规则，监督、检查实施情况；组织对注册会计师的任职资格、注册会计师和会计师事务所的执业情况进行年度检查等。', 'http://www.sogou.com/link?url=DSOYnZeCC_rPvZUv-Lv7q1oov_MuMQYQreaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('78', '中国载人航天官方网站', '科技界政协委员：中国准备迎接“太空经济... 美国宇航局三万美元奖励废弃物收集系统设计 美国航空航天安全顾问委员会公布2016年度分析报告 科学家成功完成国际空间站果蝇培...', 'http://www.sogou.com/link?url=DSOYnZeCC_oFNVZ1KD6iJyJ667Hf7_oz&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('79', '军事-中华网-中国最大的军事网站', '中华网军事频道是全国最大的军事网站，主要有以下栏目：军事要闻、台海形势、中国军情、国际军情、军事专题、论坛军帖精选、网... 详文最近，有关中国步枪的问题再一次引起了军迷们的关注，因为连续曝光了三款新式步枪，三款枪明显不是同一型号。详文其实在也...', 'http://www.sogou.com/link?url=58p16RfDRLtAsNWPWn4uAI6ofMVIc3hPG_H1iKm2_78.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('80', '中国权威专业期货门户', '当前市场环境与2003年有些类似，尽管路径可能依然曲折，中国有望在2010-2015年长周期调整后正在迈向新周期的起点。我们认为当... 提供各期货公司、交易所、财经媒体的期货相关资讯和行情报价。', 'http://www.sogou.com/link?url=1N5bSpvo44PjGIKGDJi4VYJn_hGYU_Upbhhp9J6i36M.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('81', '中国保险监督管理委员会 > 首页', '2016年保险标准化工作成效显著 关于对昆仑健康保险股份有限公司股权有... 全面落实“保险业姓保、保监会姓监”推... 中国保监会全面启动保险法人机构公司治... 中国保监会关于...', 'http://www.sogou.com/link?url=DSOYnZeCC_o1M2xSBCOeAIjgkjmF28oAhrgXYkQGDGduGGn0nqLfow..&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('82', '中国日报（Chinadaily）-China Daily Website - Connecting C...', '中国日报英文网站，内容包括国际时政新闻、突发事件、奇闻趣事等。China Daily, established in 1981, is the only national English-language newspaper in China. The average daily circulation is more than 200,000, one-third of which is abroad in more than 150 coun', 'http://www.sogou.com/link?url=DSOYnZeCC_rz88Xns-EirOA9UTWGHaeHt0YRX_nR8xs.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('83', '中国人事考试网--人民网', '经济专业技术资格考试 全国专业技术人员计算机应用能力考试 管理咨询师职业水平考试 中华人民共和国建设部第167号令 关于印发《... 人力资源和社会保障部人事考试中心是直接隶属于人力资源和社会保障部的事业单位。按照部赋予的职能，人事考试中心主要承担公务...', 'http://www.sogou.com/link?url=DSOYnZeCC_r6fpdrRK8Klvo8k9PSv4Fv&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('84', '中国国情_中国网', '“中国国情”是中外网民了解和认识中国的百科全书，最具权威性和影响力的“网上中国”。“中国国情”着力打造中国政要、政务信息、中国数据、地方概览、中国简况、国情问...', 'http://www.sogou.com/link?url=MRoBrhLn5VPLali-CpCufXArNCk6SH1eUTfpq9Q71xA.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('85', '首页-中国天气网', '中国天气网官方权威发布天气预报，逐三小时天气预报，提供天气预报查询一周，天气预报15天查询，天气预报40天查询，空气质量，生活指数，旅游出行，交通天气等查询服务', 'http://www.sogou.com/link?url=DSOYnZeCC_oXK0n85IKhX8ZmoRA401mjxcLO2TQn7Ac.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('86', '中国高等教育学生信息网（学信网）', '• 学籍学历信息管理 • 来华留学生学籍学历管理 • 阳光高考信息平台 • 中国研究生招生信息网 • 高校学生资助信息管理 • 政法干... 教育部指定的学历查询唯一网站、教育部高校招生阳光工程指定网站、全国硕士研究生招生报名和调剂指定网站。', 'http://www.sogou.com/link?url=DSOYnZeCC_qn6OMStRbQM_o8k9PSv4Fv&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('87', '住房和城乡建设部中国建造师网', '中国建造师网（www.coc.gov.cn）是住房和城乡建设部建筑市场监管司主办的全国建造师统一管理的网站。中国建造师网为了加强建设工程项目管理， 提高工程项目总承包及施工...', 'http://www.sogou.com/link?url=DSOYnZeCC_rbXFO7E0cjTVv-_as2MUne&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('88', '联盟中国', '联盟中国作为中国网主力频道之一，具有权威性高、公信力强、受众覆盖范围广的特点，目前包含媒体联盟、消费联盟和城市联盟，汇总全国媒体信息资讯、报道各级政府的新闻，解读消费行业热点话题，是为中国经济、社会、城市发展提供宣传服务的综合性频道', 'http://www.sogou.com/link?url=IPi47MzqYJ5c1Ldbs5L9xXCCPVCqv2qaxcLO2TQn7Ac.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('89', '中国西藏', '《中国西藏杂志社》网站。 根据《关于开展新闻记者证2016年度核验工作的通知》要求，中国西藏杂志社成立了记者证核验小组，对记者证严格核验。 [详细] 作者生物学博士马修·...', 'http://www.sogou.com/link?url=DSOYnZeCC_qR9kxFLnkgJiw1YAPSlpjUsv8EFten0Aw.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('90', '感恩中国', '感恩中国网 感恩网 感恩中国论坛 感恩博客 助学网站 求助网站 公益网站 慈善网站 爱心网站 寻人网站 感动中国 纪实摄影 求助报道 图片故事 美丽中国 张仁杰 纪实 新闻', 'http://www.sogou.com/link?url=DSOYnZeCC_qGT9FaOajkJwDydjxbYhws&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('91', '[中财网]-中国第一专业网络财经传媒', '中国财经信息网，24小时提供全面及时的财经新闻、数据、统计图表，财经分析软件等。包括了股票， 基金， 债券， 理财， 宏观经济， 期货， 外汇， 行业产经， 资本， 银行， ...', 'http://www.sogou.com/link?url=DSOYnZeCC_rOYJpgJHKaORuLCYv2M7L0&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('92', '中国中医药网', '中国中药协会探索亳白芍产地初加工标准 大百科全书中医药编委会召开第二次会议 长春中医药大学联手中科院开展中医科研 江西上饶建设基层特色中医馆 甘肃中医药大学校长获“...', 'http://www.sogou.com/link?url=DSOYnZeCC_porjdw1Q0-VydQRoztLvNXreaVHN88tHY.&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('93', '中国集邮信息网', '中国集邮信息网 《京津冀协同发展》3月9日发行 在京津冀协同发展战略实施三周年之际，中国邮政将于本月9日发行《京津冀协同发展》特种邮票1套3枚，同时发行小全... 辽宁省朝...', 'http://www.sogou.com/link?url=DSOYnZeCC_pZRg3vooXyqkOoWMJdhXxP&query=%E4%B8%AD%E5%9B%BD', '中国');
INSERT INTO `searchitem` VALUES ('94', '陈晓萌-软绵绵的微博_微博', '陈晓萌-软绵绵，\"知名车模 第46届国际小姐中国赛区总决赛亚军。陈晓萌-软绵绵的微博主页、个人资料、相册。新浪微博，随时随地分享身边的新鲜事儿。', 'http://www.weibo.com/cxmpd', '陈晓猛');
INSERT INTO `searchitem` VALUES ('95', '导入的项目eclipse出现乱码的处理方法 - 陈晓猛 - 博客园', '陈晓猛 博客园 首页 新随笔 联系 订阅 管理 随笔 - 37 文章 - 1 评论 - 0 导入的项目eclipse出现乱码的处理方法 如果这样子还是出现乱码无法解决的话，则删掉当前 ...', 'http://www.cnblogs.com/chenxiaomeng/p/6520466.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('96', '1. EasyUI 学习总结（一）——对话框dialog - 陈晓猛 - 博客园', '陈晓猛 博客园 首页 新随笔 联系 订阅 管理 随笔 - 37 文章 - 1 评论 - 0 1. EasyUI 学习总结（一）——对话框dialog 文章参考来源：http://www.cnblogs.com/xdp-gacl/p ...', 'http://www.cnblogs.com/chenxiaomeng/p/5804004.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('97', '陈晓猛 有多少陈晓猛,陈晓猛同名同姓-人人网 校内', '全国有多少陈晓猛？陈晓猛都来自哪儿，是男生还是女生？陈晓猛姓名的五行八字得分如何？查找和结识同名同姓的陈晓猛, 了解陈晓猛姓名吉凶，从人人网 校内开始。', 'http://name.renren.com/chenxiaomeng19719852', '陈晓猛');
INSERT INTO `searchitem` VALUES ('98', '陈晓萌 有多少陈晓萌,陈晓萌同名同姓-人人网 校内', '全国有多少陈晓萌？陈晓萌都来自哪儿，是男生还是女生？陈晓萌姓名的五行八字得分如何？查找和结识同名同姓的陈晓萌, 了解陈晓萌姓名吉凶，从人人网 校内开始。', 'http://name.renren.com/chenxiaomeng67271', '陈晓猛');
INSERT INTO `searchitem` VALUES ('99', '车模陈晓萌微博_车模陈晓萌图片_车模资料库_新浪网', '新浪汽车车模资料库为您提供车模陈晓萌详尽资料，陈晓萌高清美图，陈晓萌最新微博信息，陈晓萌车展美图。关注陈晓萌，请访问新浪汽车车模资料库。', 'http://model.auto.sina.com.cn/info/2/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('100', '基于RabbitMQ的Node.js和Python通信实例 - 博文视点', '活动获奖名单公布 恭喜以下10位读者朋友获得本次试读员征集的名额，请私信 陈晓猛 将您的QQ号发给小编，以便加入读者VIP群，给您送出图书！ 获奖名单 程续缘 ...', 'http://www.broadview.com.cn/article/17', '陈晓猛');
INSERT INTO `searchitem` VALUES ('101', '陈晓猛商铺|13083320800|主营', '陈晓猛商铺[13083320800]位于安徽 滁州 腰脯镇,,0550-3972275,如需购买,请联系陈晓猛我们竭诚为大家服务，真诚期待您的来电与咨询', 'http://13083320800.huamu.cn/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('102', '陈晓萌_新浪博客', '2012-1-10 · 陈晓萌_新浪博客,陈晓萌,投诉申通,度假中,备战广州,回到blog的日子吧,我的微博 http://t.sina.com.cn/cxmpd,车展归来（长春 武汉 成都 哈尔滨 昆明 重庆 南京 ...', 'http://blog.sina.com.cn/cxmlw', '陈晓猛');
INSERT INTO `searchitem` VALUES ('103', '周晓猛 - 百度百科 全球最大中文百科全书', '周晓猛：男，工学博士，南开大学环境科学与工程学院副教授专业：安全技术及工程从事的研究方向：火灾防治关键技术研究；应急管理技术研究；安全规划与环境预警 ...', 'http://baike.baidu.com/view/9899920.htm', '陈晓猛');
INSERT INTO `searchitem` VALUES ('104', '陈晓猛盗窃案 - 法律案例 - 中国法律案例法律门户网站 - 法律 …', '北京市平谷区人民法院 刑 事 判 决 书 （2007）平刑初字第26号 公诉机关北京市平谷区人民检察院。 被告人陈晓猛，男，1988年5月16日出生于河北 ...', 'http://anli.lawtime.cn/xsxfal/20111026215753.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('105', '刘晓猛 有多少刘晓猛,刘晓猛同名同姓-人人网 校内', '全国有多少刘晓猛？刘晓猛都来自哪儿，是男生还是女生？刘晓猛姓名的五行八字得分如何？查找和结识同名同姓的刘晓猛, 了解刘晓猛姓名吉凶，从人人网 校内开始。', 'http://name.renren.com/liuxiaomeng20039281', '陈晓猛');
INSERT INTO `searchitem` VALUES ('106', '博文陈晓猛 - 开源中国(OSChina.NET)', '博文陈晓猛 回复了话题：六大手游开发引擎优劣分析', 'http://m.oschina.net/u/1762879', '陈晓猛');
INSERT INTO `searchitem` VALUES ('107', '博文陈晓猛的关注 - 开源中国社区', '博文陈晓猛 电子工业出版社 - 项目经理 北京 - 丰台 博文陈晓猛 很懒，签名啥也没写 关注 私信 提问 积分 0 粉丝 0 关注 32 加入于 2014/04/30 最近登录：2016/03/04 10 1 ...', 'http://my.oschina.net/u/1762879/fellow?sort=time', '陈晓猛');
INSERT INTO `searchitem` VALUES ('108', '【分享】Html5 Video 实现方案 - DCloud问答', '陈晓猛 请问一下内联样式，在android机上运行的时候，点击全屏没办法横屏全屏播放，这个有什么解决的方法吗？ 0 赞 2016-08-18 15:15 NewsNing 回复 陈晓猛 请看我的 ...', 'http://ask.dcloud.net.cn/article/569', '陈晓猛');
INSERT INTO `searchitem` VALUES ('109', '在阿里云容器服务上开发基于Docker的Spring Cloud微服务 ...', '李老师您好，我是电子工业出版社博文视点的编辑陈晓猛，在社区看到您发表的很多关于微服务方面的文章，觉得内容很好，不知道您是否有兴趣出版这方面题材 ...', 'https://yq.aliyun.com/articles/57265', '陈晓猛');
INSERT INTO `searchitem` VALUES ('110', '末世空间法则 第八十五章 姐姐， 我肚子饿 _ 2k小说阅读网 ...', '陈晓猛 的冲进去，看到聂天正蹲在地上，手忙脚乱的把散落了一地的药材想捧到刚才被他用力过猛，拉的掉在地上的木盒子里去。 陈晓长舒一口气，还好，他没事 ...', 'http://2kxs.com/xiaoshuo/74/74503/13739284.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('111', '末世空间法则 第二百零四章 洞房花烛夜 _ 2k小说阅读网 ...', '只到陈晓猛 的把门打开，屋外的人身子一歪，就倒了进来。陈晓被吓的清醒了一下下，扶着倒进来的身子，还没扶好，她就觉得自己浑身发软，哪还有力气去扶人 ...', 'http://www.2kxs.com/xiaoshuo/74/74503/15078851.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('112', '老秦建筑工程', '在校学员陈晓猛：CAD构件图 在校学员栾晓阳：PPT作业 在校学员张宇晴：Word制作请柬 在校学员万彦杰：Tekla图 在校学员安康：门钢图 在校学员刘晓恒 ...', 'http://www.laoqin.net/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('113', '【分享】Html5 Video 实现方案 - DCloud问答', '陈晓猛 请问一下内联样式，在android机上运行的时候，点击全屏没办法横屏全屏播放，这个有什么解决的方法吗？ 0 赞 2016-08-18 15:15 NewsNing 回复 陈晓猛 请看我的 ...', 'http://ask.dcloud.net.cn/article/569', '陈晓猛');
INSERT INTO `searchitem` VALUES ('114', '末世空间法则 第八十五章 姐姐， 我肚子饿 _ 2k小说阅读网 ...', '陈晓猛 的冲进去，看到聂天正蹲在地上，手忙脚乱的把散落了一地的药材想捧到刚才被他用力过猛，拉的掉在地上的木盒子里去。 陈晓长舒一口气，还好，他没事 ...', 'http://2kxs.com/xiaoshuo/74/74503/13739284.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('115', '老秦建筑工程', '在校学员陈晓猛：CAD构件图 在校学员栾晓阳：PPT作业 在校学员张宇晴：Word制作请柬 在校学员万彦杰：Tekla图 在校学员安康：门钢图 在校学员刘晓恒 ...', 'http://www.laoqin.net/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('116', '【爱有天意、颖晓】一笑心晴（颖晓文）_陈晓赵丽颖吧 ...', '你干什么！走，我们回宾馆说！”丽颖甩开他的手道“说什么，你还是去找你的周妹妹吧！”陈晓猛 的拉住她往宾馆走去。丽颖还在拼命的挣扎。陈晓道“你要是再闹 ...', 'http://tieba.baidu.com/p/2427690372', '陈晓猛');
INSERT INTO `searchitem` VALUES ('117', '【130818★颖晓】如果没有你_陈晓赵丽颖吧_百度贴吧', '陈晓猛 的抬头，想开口，最终却什么也没有说。看来，没有什么是不可以改变的呢。-中午的一顿饭，两个人都吃得味同嚼蜡，到了片场之后就马上开始化妆，也没有时间 ...', 'http://tieba.baidu.com/p/2538964682?see_lz=1', '陈晓猛');
INSERT INTO `searchitem` VALUES ('118', 'STC15增强型8051单片机C语言编程与应用（含CD光盘1张 ...', '宏晶科技有限公司总经理姚永平先生提供了 STC15单片机测试样片，电子工业出版社的孙学瑛和陈晓猛 编辑提出了许多宝贵意见，彭秀华、徐阳、范林、郑玉章、李涛、杨 ...', 'http://baike.baidu.com/view/15195905.htm', '陈晓猛');
INSERT INTO `searchitem` VALUES ('119', '09年国美新司机陈晓猛踩刹车的原因', '09年国美新司机陈晓猛踩刹车的原因 09年国美新司机陈晓猛踩刹车的原因 2008年11月，国美创始人黄光裕被警方带走调查，而其麾下的全国上千家门店，几十万 ...', 'https://www.douban.com/note/89782528/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('120', '601877:正泰电器:股权激励验资报告_正泰电器(601877)_公告 …', '9,750.00 119,340.00 肖凌 129,090.00 129,090.00 2017/2/13 9,750.00 119,340.00 陈晓猛 129,090.00 129,090.00 2017/2/15 9,750 上游 129,090.00 129,090.00 ...', 'http://data.eastmoney.com/Notice/20170311/2Wvl2df6JKZxd9.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('121', '南京工业大学校长办公室 | xb.njtech.edu.cn', '陈晓猛 1 月 25 日 (一) 高 明 李承林 1 月 26 日 (二) 朱跃钊 米 展 1 月 27 日 (三) 黄 维 吴贵明 1 月 28 日 (四) 王德明 陈浩春 1 月 29 日 (五) 吴胜红 李晓冬 1 月 30 日 ...', 'http://xb.njtech.edu.cn/view.asp?id=263&class=18', '陈晓猛');
INSERT INTO `searchitem` VALUES ('122', '博文陈晓猛的个人空间 - 开源中国社区', '博文陈晓猛的个人空间, 首页 开源项目 国产开源项目 项目分类 最新收录项目 Java 开源软件 C# 开源软件 PHP 开源软件 C/C++ 开源软件 Ruby 开源软件 ...', 'http://my.oschina.net/u/1762879', '陈晓猛');
INSERT INTO `searchitem` VALUES ('123', 'PostgreSQL查询引擎源码技术探析', 'PostgreSQL作为当今最先进的开源关系型数据库，本书揭示PostgreSQL查询引擎运行原理和实现技术细节，其中包括：基础数据结构；SQL词法语法分析及查询语法树；查询 ...', 'http://www.phei.com.cn/module/goods/wssd_content.jsp?bookid=47188', '陈晓猛');
INSERT INTO `searchitem` VALUES ('124', '发表回帖的评论 - 开源中国(OSChina.NET)', '博文陈晓猛: 写的比较全面', 'http://m.oschina.net/blog/reply?cmt=282706196', '陈晓猛');
INSERT INTO `searchitem` VALUES ('125', '陈凌婷 | 陈葆峰 | People Directory', '陈晓猛 - 陈晨钟 陈晨阳 - 陈智秋 陈智科 - 陈月熙 陈月燕 - 陈木成 陈木文 - 陈来熠 陈来燕 - 陈林周 陈林和 - 陈柏瑾 陈柏甫 - 陈栋杰 陈栋松 - 陈桂超 陈桂辉 - 陈梓航 ...', 'https://www.amol.a.c.c.facebook.com/directory/people/24-6730543-6788068', '陈晓猛');
INSERT INTO `searchitem` VALUES ('126', 'OpenCV图像处理编程实例', '本书以OpenCV开源库为基础实现图像处理领域的 很多通用算法，并结合当今图像处理领域前沿技术，对多个典型工程实例进行讲解及实现。全书内容覆盖面广，由基础到进阶 ...', 'http://www.phei.com.cn/module/goods/wssd_content.jsp?bookid=46366', '陈晓猛');
INSERT INTO `searchitem` VALUES ('127', 'PostgreSQL查询引擎源码技术探析 - china-pub网上书店', '书籍 计算机书籍 PostgreSQL作为当今最先进的开源关系型数据库，《PostgreSQL查询引擎源码技术探析》揭示PostgreSQL查询引擎的运行原理和实现技术 ...', 'http://product.china-pub.com/4975165', '陈晓猛');
INSERT INTO `searchitem` VALUES ('128', '速迈软件|速迈软件网站', '陈晓猛 先生 关注八方营销微信 助你马上赚钱 会员编号：1700323 八方币：1000 荣誉认证：0项 信息满意度：100% 认证： 未认证营业执照 未认证身份证 所在地区 ...', 'http://chen1984617.cn.b2b168.com/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('129', '南京工业大学党委组织部', '支部书记陈晓猛 传达了学校“‘两学一做’学习教育动员大会”会议精神，围绕“目标要求”、“主要任务”、“方法措施”、“组织领导”和“开展学习教育 ...', 'http://zzb.njtech.edu.cn/Home/Content/getContent/id/775.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('130', '青岛凯佳兴国际物流有限公司_欢迎您！', '联系人：陈晓猛 先生 手 机： 15092097698 电 话： 传 真： E_Mail：289707739@qq.com QQ： MSN： 地 址： 安全警示： 合作要有安全意识，需当面核实对方 ...', 'http://www.shop26937.haoyun56.com/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('131', '南京工业大学党委办公室 | db.njtech.edu.cn', '陈晓猛 同志任资源保障部副部长、实验室管理办公室主任； 朱兴同同志任校园安全部部长； 韩少寅同志任校园安全部副部长； 浩洪涛同志任校园安全部副部长 ...', 'http://db.njtech.edu.cn/view.asp?ID=712&page=0&class=38', '陈晓猛');
INSERT INTO `searchitem` VALUES ('132', '评奖评优 - 浙江大学经济学院', '任晓猛 21201039 张睿楠 11201020 张馨羽 21201070 单丹丹 21201041 王辰 21201072 韦星 荣誉称号 优秀研究生 11001005 张晶晶 21201010 祁越 11001007 蒋墨冰 ...', 'http://www.cec.zju.edu.cn/redir.php?catalog_id=11798&object_id=71117', '陈晓猛');
INSERT INTO `searchitem` VALUES ('133', '南京工业大学-材料科学与工程学院', '”第十二届陶艺大赛在历时两个多月，终于圆满落下了帷幕。校资产处副处长陈晓猛 、教务处副处长钱小明、校团委副书记费军、材料学院副院长陆春华以及学院 ...', 'http://cly.njtech.edu.cn/view.asp?id=5341&leibie2=152', '陈晓猛');
INSERT INTO `searchitem` VALUES ('134', '南京工业大学校长办公室 | xb.njtech.edu.cn', '陈晓猛 8月22 日(五) 吴胜红 陈才华 8月1日(五) 张进明 刘思华 8月23日(六) 邢卫红 张文进 8月2日(六) 崔益虎 李志跃 8月24日(日) 巩建鸣 黄步军 8月3日(日) 蒋军成 米 展 ...', 'http://xb.njtech.edu.cn/view.asp?id=59&class=18', '陈晓猛');
INSERT INTO `searchitem` VALUES ('135', '【陈晓】_名品导购网陈晓专区', '09年国美新司机陈晓猛踩刹车的原因 作者：太阳红雨 2010-08-17 09年国美新司机陈晓猛踩刹车的原因 2008年11 月，国美创始人黄光裕被警方带走调查，而其麾下的全国 ...', 'http://www.mplife.com/k/19848/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('136', '杨晓猛电影全集_杨晓猛演过的电视剧-爱奇艺明星资料页', '爱奇艺杨晓猛个人资料页提供杨晓猛相关资料，杨晓猛最新电影及杨晓猛电视剧等视频作品在线观看。杨晓猛简介：内陆演员。', 'http://www.iqiyi.com/lib/s_204383805.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('137', '青岛凯佳兴国际物流有限公司_欢迎您！', '联系人：陈晓猛 先生 手 机： 15092097698 电 话： 传 真： E_Mail：289707739@qq.com QQ： MSN： 地 址： 安全警示： 合作要有安全意识，需当面核实对方 ...', 'http://www.shop26937.haoyun56.com/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('138', '《STC15增强型8051单片机C语言编程与应用(含CD光盘1张 ...', '本书详细介绍了宏晶科技有限公司研发的STC15系列新型Flash 8051单片机的基本组成、性能特点及应用方法，基于Flash存储器的ISP在系统中编程和IAP在应用中编程的相关 ...', 'http://www.wl.cn/8325793', '陈晓猛');
INSERT INTO `searchitem` VALUES ('139', '发表回帖的评论 - 开源中国(OSChina.NET)', '博文陈晓猛: 8000万。MOMO', 'http://m.oschina.net/blog/reply?cmt=282275310', '陈晓猛');
INSERT INTO `searchitem` VALUES ('140', '南京工业大学资源保障部 | wzc.njtech.edu.cn', '4 月8日上午，南通大学国有资产与实验室管理处处长管图华、副处长徐晓艳等一行来我校考察交流。资源保障部部长蔡海彪、副部长陈晓猛与来访客人进行会谈 ...', 'http://wzc.njtech.edu.cn/new/view.asp?id=1619&class=997', '陈晓猛');
INSERT INTO `searchitem` VALUES ('141', '速迈软件|速迈软件网站', '陈晓猛 先生 关注八方营销微信 助你马上赚钱 会员编号：1700323 八方币：1000 荣誉认证：0项 信息满意度：100% 认证： 未认证营业执照 未认证身份证 所在地区 ...', 'http://chen1984617.cn.b2b168.com/', '陈晓猛');
INSERT INTO `searchitem` VALUES ('142', '轻量级微服务架构PDF下载|轻量级微服务架构(一)黄勇百度网 ...', '感谢电子工业出版社博文视点的陈晓猛 编辑，在写作过程中晓猛多次鼓励我，他曾说“写书就是登山”，每当我写不动了，想放弃了，他就会鼓励我“快到山顶了 ...', 'http://www.yxdown.com/soft/274221.html', '陈晓猛');
INSERT INTO `searchitem` VALUES ('143', '陈晓猛盗窃案 - 判裁案例 - 110网', '公开开庭进行了审理。被告人陈晓猛到庭参加诉讼。现已审理终结。 公诉机关指控： 1、2006年5月21日14时许，被告人陈晓猛用事先准备好的撬棍，采用撬木门等手段，进入平谷...', 'http://www.sogou.com/link?url=DSOYnZeCC_pHOGfPNIi0JFTCVUBuyQJp-0wJVt1q6a3d3pY5N3elLa4to0wa_Tif&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('144', '陈晓猛：听了一下午的老歌 才...', '陈晓猛：听了一下午的老歌 才发现回不去了。#分享音乐# #说谎-林宥嘉# http://url.cn/0GlyUB 腾讯微博，与其在别处仰望 不如在这里并肩', 'http://www.sogou.com/link?url=a8xlm0X2uveSPNOcFgyr3ZzUc_otlaFADLa5WnvBvAQpJmFtPId_gg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('145', '陈晓猛 - 博客园', '摘要： 1，网络编程/网站编程：敲一个网站，别人可以访问 访问：在地址栏里面敲入地址，就可以访问了。 服务器如果放在公网，那么别人就可以通过IP地址进行访问 所以我们可...', 'http://www.sogou.com/link?url=DSOYnZeCC_rR_TP93bdO6Es25fHsmGYR3lbqvy3uNNUMTQb2Jz0n4Q..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('146', '看到陈晓猛我就回复个傻吊,我这是什么心态？_石榴高级中学吧_百...', '36条回帖 - 发帖时间：2012-05-07', 'http://www.sogou.com/link?url=a8xlm0X2uvcGBOx2SiCYwgu4602TJj_cBxlC5b28TTRJyXTKMIREeA..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('147', '陈晓猛：年底就是跟兄弟们激情...', '陈晓猛：年底就是跟兄弟们激情四射的时光啊，就是总是不齐呀。腾讯微博，与其在别处仰望 不如在这里并肩', 'http://www.sogou.com/link?url=a8xlm0X2uveSPNOcFgyr3Q9TjQ0otTfZn1xwLYePz0fIGRb_vUALcg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('148', '09年国美新司机陈晓猛踩刹车的原因', '09年国美新司机陈晓猛踩刹车的原因 09年国美新司机陈晓猛踩刹车的原因 2008年11月，国美创始人黄光裕被警方带走调查，而其麾下的全国上千家门店，几十万员工何去何从当时...', 'http://www.sogou.com/link?url=DSOYnZeCC_oPL4RhSawS88xtTWigSzwgUWWjJtee_VL1tEyX3XwueClxG-H3pRuC&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('149', '博文陈晓猛的个人空间 - 开源中国社区', '资讯 移动开发 Android开发专区 iOS开发专区 iOS代码库 Windows Phone 招聘 城市圈 登录 加入开源中国 登录 加入开源中国 博文陈晓猛的空间 博文陈晓猛 关于我们 广告联系 @新...', 'http://www.sogou.com/link?url=58p16RfDRLvsgRwZ6iNBPowMFC8tI1AOvyEGOTEEoplP3Df1pu14kN4TiL8T41iu&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('150', '陈晓猛-我的博文 - 博文视点', '陈晓猛 导语： CoreOS官网主页使用一句话概括其理念：“A newway to think about servers”，以及紧接着的“CoreOS is Linux for massive server deployments”， 表示... 陈晓猛 ...', 'http://www.sogou.com/link?url=DSOYnZeCC_oVzK0lG-NWo-bnLJig4kIYVk5H0sM5JnsnLkFCA2Ck8q6X_ODNIzZP&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('151', '陈晓猛的朋友印象', '扫码下载 » 下载朋友印象APP 印象 浏览 停留 7s 赞 朋友 评论 竟然是空的！ 下载手机版可以为TA添加内容 Copyright © 2016,Shanghai Yueren IT Co., Ltd. 上海阅人信息技术有限...', 'http://www.sogou.com/link?url=DSOYnZeCC_qdBr0ZzxHKcbmGMleRvCG1O54Gj9BQm4yAGHpGTEjxOvFrXf7c6ovK&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('152', '错误记录 - 陈晓猛 - 博客园', 'web.xml没有配置会导致404错误 $.ajax option是一个对象， ①先定义一个form，提交的时候，.submit就可以提交 可能是在后台建立了隐藏的iframe提交 $（\'#ff\'）.form({ url:.. ...', 'http://www.sogou.com/link?url=DSOYnZeCC_rR_TP93bdO6Es25fHsmGYR3lbqvy3uNNW8QnCVxXjHCVgR7E3QZEznIeZ8aQ291kY.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('153', '陈晓猛的电影', '[图文]豆瓣 我们的精神角落 扫码直接下载 豆瓣 4.0 全新发布 想看 · · · （1部）', 'http://www.sogou.com/link?url=hedJjaC291PRk6U3MmR8l1gSvBeWzmiQYoLw4keiADOf29Plhnsm1m4YafSeot-j&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('154', '陈晓猛的个人主页-阿里巴巴1688.com', '欢迎来到阿里巴巴 进货单中暂未添加任何货品 特色市场 采购平台 常用工具 对他感兴趣吗？不想错过他的动态，就先关注吧亲~ 先生 这家伙很神秘，未留下任何踪迹！ 社区行为 （...', 'http://www.sogou.com/link?url=58p16RfDRLtvv-_HRtBqpT-MbTaTYKslP_2BM19T_Y4.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('155', '陈晓猛：#这里是广西#地处祖国...', '陈晓猛：#这里是广西#地处祖国南疆，位于东经104°26\'—112°04\'，北纬20°54\'—26°24\'之间。西南地区最便捷的出海通道，中国西部资源型经济与东南开放型经济的结合部。全自...', 'http://www.sogou.com/link?url=a8xlm0X2uveSPNOcFgyr3ehyu0caji8TgdH0zmUbJup2eqxKbvwb-w..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('156', '【精品】陈晓猛论文 - 道客巴巴', 'Word文档 - 18页 - 下载需要820积分', 'http://www.sogou.com/link?url=DSOYnZeCC_orOCecstjRvD3faEttgpPBq3Cu4-0vFErOtcQGoB61xa4to0wa_Tif&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('157', '陈晓猛：#国人健康赤字#那也是...', '陈晓猛：#国人健康赤字#那也是拜改革开放快速发展经济所赐，要赶上一个时代，总得牺牲几代人。现在已经从多方面反映出影响健康问题，解决这些问题需要时间，会好的。腾讯...', 'http://www.sogou.com/link?url=a8xlm0X2uveSPNOcFgyr3TCD_GkxyKhCgNQzU411YXkExojA547oBCtQkiCE3T9N&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('158', '09年国美新司机陈晓猛踩刹车的原因_金融聚焦_中华网论坛--网友影响...', '09年国美新司机陈晓猛踩刹车的原因 2008年11月，国美创始人黄光裕被警方带走调查，而其麾下的全国上千家门店，几十万员工何去何从当时成为了最大的悬疑。而在陈晓接掌国...', 'http://www.sogou.com/link?url=6YUuC6e6hWbmbLnCiMcAEC2yExt7sESWH1TgQFn9y8DqJzZRwHegMYuOJtKZNkKYoTdaNJCwu4kh5nxpDb3WRg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('159', '陈晓猛论文.doc - 豆丁网', 'Word文档 - ', 'http://www.sogou.com/link?url=DSOYnZeCC_qmZv6AVu39pVh-h8gOyXEMCB3Vt5_Z2x04d2X6F0SQYA..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('160', 'css-关于位置 - 陈晓猛 - 博客园', '随笔 - 35 文章 - 1 评论 - 0 当你设置一个你想要相对的模块为relative 你这个模块为absolute 则你的这个absolute会相对relative的那个模块进行移动。', 'http://www.sogou.com/link?url=DSOYnZeCC_rR_TP93bdO6Es25fHsmGYR3lbqvy3uNNV6fgX_HYjc1lRFZ4DD13RTIeZ8aQ291kY.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('161', '导入的项目eclipse出现乱码的处理方法 - 陈晓猛 - 博客园', '[图文]随笔 - 37 文章 - 1 评论 - 0 如果这样子还是出现乱码无法解决的话，则删掉当前项目重新开始项目。', 'http://www.sogou.com/link?url=DSOYnZeCC_rR_TP93bdO6Es25fHsmGYR3lbqvy3uNNW4eciUhBLt4OwB45bk8ACOIeZ8aQ291kY.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('162', '【陈晓猛-结构/土木土建工程师2000-3000元】 - 石家庄桥东建筑/装修 - ...', '【陈】先生，【24岁】，学历【大专】，已有【1-2年】工作经验，欲在【桥东】找工作一份，有意者请与我联系，非诚勿扰。', 'http://www.sogou.com/link?url=LeoKdSZoUyDUwEN6fxk39djrS9MsOidE-xB1t4QZ7z45MyodF4EGPwZFJ5UQUXQ3&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('163', '招商银行股份有限公司信用卡中心诉陈晓猛信用卡纠纷一审裁定书', '招商银行股份有限公司信用卡中心诉陈晓猛信用卡纠纷一审裁定书详情，点击即可查看.天眼查提供企业法律诉讼信息查询，是一款服务于个人的企业信息查询系统', 'http://www.sogou.com/link?url=DSOYnZeCC_qbhB5TwFUHrSv1MbFsrL0I95OGtWEurJ9zpaXeyyV-lKK-2xjFHUe08A1WLNCLToFaoasL5hcM_c-TMWPlj8HD&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('164', '孝感槐荫论坛-槐荫侃吧-09年国美新司机陈晓猛踩刹车的原因', '孝感槐荫论坛槐荫侃吧[：：槐荫树下：：]09年国美新司机陈晓猛踩刹车的原因09年国美新司机陈晓猛踩刹车的原因2008年11月，国美创始人黄光裕被警方带走调查，而其麾下的全...', 'http://www.sogou.com/link?url=DSOYnZeCC_qOuljkl0KCcSJuu9jpB0wVVVzEn7ag5SsIuM5enNRZhRY1zdj0Pe4M&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('165', '广西合山市闽鑫特殊钢有限公司 联系人：陈晓猛 联系电话：86-0772-...', '[图文]公司黄页面包屑 首页 >公司黄页 > 广西合山市闽鑫特殊钢有限公司 公司简介 广西合山市闽鑫特殊钢有限公司是一家冶金矿产的企业，是经国家相关部门批准注册的企业，是一...', 'http://www.sogou.com/link?url=6YUuC6e6hWa3gNvbXPcGtrXlWxlxUBho2COATDIgHRpvCMiDcKDLFSUc_EC-XODJ8OoV1qZUWYvU2WaFq3NdE2i2w7QwQH-kTCCRnNbbDu7bYEzU1gUYPPx-JLIuZ7uLZEVvOljqW4E4KkmSZRdgn0c8W9Tw7tgBqD4g-C6wfNpBRV5emjIy3K3mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('166', '江苏沭阳木业有限公司 联系人：陈晓猛 联系电话：86-0527-62277739 ...', '公司黄页面包屑 首页 >公司黄页 > 江苏沭阳木业有限公司 公司简介 江苏沭阳木业有限公司 位于江苏 沭阳县，主营 物流的相关软件 等。公司秉承“顾客至上，锐意进取”的经营理...', 'http://www.sogou.com/link?url=6YUuC6e6hWa3gNvbXPcGtrXlWxlxUBho2COATDIgHRojWteCDO0yUPbmtPcvl9iyxRiBsFonEoHUqUHlMDgz_K3mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('167', '广西合山市闽鑫特殊钢有限公司 产品列表 联系人陈晓猛 中国广西合山...', '广西合山市闽鑫特殊钢有限公司是一家冶金矿产的企业，是经国家相关部门批准注册的企业，是一家采用自主创新的高效节能新技术、新工艺，以高科技产品为龙头，以市场需求为...', 'http://www.sogou.com/link?url=DSOYnZeCC_oZvyWiE4-Z8sr20KFjVnaiiApZTciV_mkX6-0zHJLwEA..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('168', '仁怀市人民政府办公室关于成立防治人畜猪链球菌病工作协调小组的通...', '陈晓猛（市公安局副局长）丁春轩（市经贸局副局长）陈坤永（市工商局副局长）仇志华（市畜牧局副局长）领导小组下设办公室在市畜牧局，何修利同志兼任办公室主...', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgr_sHm3fiG5dVy6JvJfJZBvCJC-1zdrX6ScjGZCykckjfTJGsJ1OU7uMwm-AoDcvfqIrodgWmaGBDlkjrUABbfG40SiJ2yvnKx9Tl2xd4WdTbP6MBg3Fp4HO8r9vBvncHJf6qmricXVNh8gleqcBJOEg04IDEuYwvNSsCuzhet99KbLg_nsxX5cxQEPqW0z4q0ux8b82sKi0JX547BYWB0h0tEf94jWyRXPVvqRCNaJkfsliU2OsxgONheOfi52IlXnWz-L-_8fakfOwAifBDDxbZsacwlJOOd1PYo9PGnmS-ZpbY0_XxRzsXLdC2O23lQmRsa59hHb-Qp-FrSVEkTvvf4k_seT0SqBgz_GIjhm74B0e-7SMGDIG_qTZmIMAuy9Wg97J6PqJ6OGX_nNFpeRcHLo36J49Z&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('169', '21世纪应用型本科院校规划教材·机械制造 - 搜狗百科', '南京工业大学金工实习中心主任刘俊义主审。 本教材在编写和出版过程中，受到陈晓猛、刘培友、佘守坚、顾荣、王维新、陆新民、谢志余等领导和老师的大力帮助和支持，在此一并表示衷心感谢。 由于编者的水平和经验有限，书中难免有错误和不妥之处，敬请广大读者批评指正。', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgWB9jwpNauGhVy6JvJfJZBpLEmJm3emBY7Vki_UvSPTIV11pMUeNy7rwmgScqq8SecfSvrBMPv8uQ5B0HL7IVeE60euROTLT3XYYjff993UabuePtEo3px_KnOtjOLEhDw0mS7Q39vFU4r2LhF1xL8AIDzP8010sp9_L_b4GVmj_SOay5F4pnw0fIt1KGns5vQw_mB5IntODMXtrKOSy3kTEjY51eMCY_eFBFlOYw9nUBcdwBvb2yIK3mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('170', '文明参与交通 需要换位思考_网易新闻中心', '2012年1月11日 - 陈晓猛显然应该明白这句话的深意了。 交通是一个人人参与的项目，无论开车还是步行，一举一动都是其中一份子。而交通能否畅通，最重要的是秩序。秩序则...', 'http://www.sogou.com/link?url=6IqLFeTuIyhB8S4v2mhiQOTB0LCy-VaKQWnjYuAtTFzlUBGbvXVSnrGIyywPemxH0ztd7q5nl6o.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('171', '价值七百万五粮液保住了_新闻中心_新浪网', '[图文]民警陈晓猛急中生智,将驾驶室前倾与后部货厢分离,让火势完全向前燃烧,这才没有造成更大的经济损失.最后在遵义县消防官兵的共同努力下,将大火完全扑灭,保住了价...', 'http://www.sogou.com/link?url=6IqLFeTuIyi9rbFxuFxgXSdQRoztLvNXt1mY0mpVKOWCUGEkp0gpc-F9lml4JOzGq1Wkg5mjc1qt5pUc3zy0dg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('172', '价值七百万五粮液保住了_贵州_新闻_腾讯网', '[图文]民警陈晓猛急中生智,将驾驶室前倾与后部货厢分离,让火势完全向前燃烧,这才没有造成更大的经济损失.最后在遵义县消防官兵的共同努力下,将大火完全扑灭,保住了价...', 'http://www.sogou.com/link?url=6IqLFeTuIyjQOyGNYhR5roTP8JAeT1n3bj9j-T_wwgHR2AgvPfd3o63mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('173', '循着路上几块碎片交警逮回肇事司机_资讯频道_凤凰网', '2012年2月2日 - 陈晓猛和该面包车车主取得联系，找到面包车驾驶员联系方式。该驾驶员在电话中承认撞人，目前在云南。交警连夜赶到云南，昨日凌晨5点在曲靖抓获肇事司机...', 'http://www.sogou.com/link?url=6IqLFeTuIyh9rnnE9m9FAjy0lYG5YnaHLj_AalJHDYEb9LaFK380pUKEj3fgFZAQxcmkAxq709tU4yxyKdfgk63mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('174', '《末世》如果独舞 ˇ过渡ˇ 最新更新：2010-10-25 17:20:19', '@ 陈晓猛的刹住脚步回身用尽吃奶的力气把手中的铁杆投向丧尸。 。a2557a7b2e94197f “扑哧！”“嘶吼！！！”铁杆狠狠的扎进丧尸的眼眶，陈晓一向前猛的一冲，抓住铁杆...', 'http://www.sogou.com/link?url=DSOYnZeCC_o-rKT8gF1wNkfUi8I_-jUHV7b99QWeEHzjnk42zk2K1oB2mq2IZw-DNNqmhDcpRQ4ukoWYw2RTBw..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('175', '盗辆桑塔纳 挂个假军牌_新闻中心_新浪网', '2007年12月18日 - 民警陈晓猛、王斌接警后立即出警驾车在贵遵公路上设卡拦截。 7时许，民警发现一辆挂广A14033军牌的黑色桑塔纳轿车疑似案情通报上的车辆，遂将其拦停...', 'http://www.sogou.com/link?url=6IqLFeTuIyi9rbFxuFxgXSdQRoztLvNXBcMY2BDFWaQ9l5oBowH-GpZV7Z5Z0Iq3ZjrQVHeePsCt5pUc3zy0dg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('176', '生命定格在救人瞬间——追记贵州省交警总队直属支队贵遵四大队...', 'Word文档 - ', 'http://www.sogou.com/link?url=DSOYnZeCC_qmZv6AVu39pUschALcgEKXJsbAWtBXvcQ4d2X6F0SQYA..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('177', '要去晴隆却被带上贵遵路 黑面的“南辕北辙”_新民网_为民分忧 与民...', '[图文]2010年6月13日 - 接警后，大队民警陈晓猛和协勤立即驾车前往遵义县南白匝道口设卡拦截。 9时30分，这辆白色中型客车驶入民警视野，经检查，该车核载6人，实载20人...', 'http://www.sogou.com/link?url=6IqLFeTuIyjLG2noTx5tS-E9P8iJQ6xmRmiPrswOsBKrsaPF4NatTLO1UP6K3fb_EJW3YLTt4Fc.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('178', '贴身杀手-17 妥协-都市小说小说-17k小说网', '“陈晓猛的一拍桌子，”老实交代，你的同伙呢？“ “同伙？“苏云轩眼睛一眯，感情这位警花并不是对头势力的犬牙，实际上就是别人的一支枪，整件事的门路丝毫不知情。 “...', 'http://www.sogou.com/link?url=DSOYnZeCC_oW5DEIdvVwn7GWOtAxCTXcBUG8eCoUjsKena8_q7Cx59MO8uLvd-Er&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('179', '500辆车被堵21小时_贵州_新闻_腾讯网', '[图文]9月10日晚至11日下午,贵遵公路遵义县境内109公里路段长时间堵车,过往车辆被滞留长达21小时. 据省交警总队直属支队贵遵四大队民警介绍,由于近日来遵义地区连续阴...', 'http://www.sogou.com/link?url=6IqLFeTuIyjQOyGNYhR5roTP8JAeT1n3PVu-1NiyxAn40xcYGyI-Ca3mlRzfPLR2&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('180', '文明参与交通 需要换位思考 - 滚动新闻 - 21CN.COM', '[图文]2012年1月11日 - 我的朋友陈晓猛就被这水洼伤透了心。昨天中午，他把车开到停车场停下，打着伞沿着纱帽南街走，要去香槟广场约会。那是去见刚认识的女朋友，所以他...', 'http://www.sogou.com/link?url=6IqLFeTuIyhUu8YnWBHGXlJwyCZFRrUM6dzpHMhgliYTinL4b5vQwNmVH4HNEYlStPIGaDrXsZch5nxpDb3WRg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('181', '：： 新华网 ：： - 地方联播', '2010年2月2日 - ＂陈晓猛说，＂贵州雨多，走在施工道路上指挥交通，满裤腿都会溅上泥，别人最多溅到膝盖处，健成走路多，一天要走二十多公里，泥巴溅到大腿上，每次都...', 'http://www.sogou.com/link?url=DSOYnZeCC_rFnAdVO_Rb-VWSPSk83357biNvFGwebCDO4y69Lc9vzcDsIER_l9JBoGtP-43R2-v27056hj-qCRQ89sWzl3Yg&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('182', '2009年全国房地产估价师执业资格考试保留成绩人员名单 - 道客巴...', 'Word文档 - 1页 - 下载需要1000积分', 'http://www.sogou.com/link?url=DSOYnZeCC_orOCecstjRvFh-h8gOyXEM4JMgabe4MiXUhPScysD_X64to0wa_Tif&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('183', '高速交警宽容旅游车 轻微违法不予处罚', '2007年10月1日 - 对来黔旅游的自驾游车辆的轻微违法行为以批评教育为主，不予处罚。（李勇明 朱振 陈晓猛 周德松 唐正平 陈晓伟） 来源：贵州都市报 责编：张琳涔', 'http://www.sogou.com/link?url=DSOYnZeCC_of1jB9gcg5jtdp24KvxQCk9KBAGEqRhZzPtdWztQGO_VQopwNU_64NFzmommnQJvAF8uCT6CeQ8a4to0wa_Tif&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('184', '宁夏回族自治区', '陈晓猛 906640055 张小鹏 906640074 谢玺906640082 马兴柱 906640108 王晓霞 907640064 杨兴杰 907640113 潘继钊 907640139 张阳908640036 马思贵 908640039 贾建军 ...', 'http://www.sogou.com/link?url=DSOYnZeCC_pKZzihDKzFg2Ioibd_w6FPNq-3GTaQ8C_6EaBIbPwS0lUaqjalL83j5jg23E6qIrC5jmUG0WuLOVCYsesQQowQaVPwlUvIb-et5pUc3zy0dg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('185', '贵州25人死亡车祸原因查明：司机操作不当负主责_网易新闻中心', '2008年3月18日 - 据了解，目前，四川省司法部门已经协助死者家属委托了多名律师，组成律师团前往遵义，准备向相关部门和单位提起民事赔偿诉讼。（贵州都市报陈晓猛 唐正...', 'http://www.sogou.com/link?url=6IqLFeTuIyhB8S4v2mhiQFs6dk6T6eNyGRFU_BKKahmceomZ7K-A83_NfUA5tNUg0ztd7q5nl6o.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('186', '601877：正泰电器：股权激励验资报告_正泰电器（601877）_公告正文', '0.2151 129,090.00 129,090.00 9,750.00 0.2151 9,750.00 0.2151陈晓猛 9,750.00 0.2151 129,090.00 129,090.00 9,750.00 0.2151 9,750.00 0.2151叶上游 9,750.00 0.2151 129,090....', 'http://www.sogou.com/link?url=WaeIF24cBDu3hP1y3b24hf4T17ln4fKRU9XqVi5mBWMsmMIWboNDZZpvYEBtmm514EQush3ynOuCS4Xu9PJvPFkZ5EPxXpdx-BnUboBPgn4TcwNOkb18MXBCDTEvaOXJjFDedYYCbFrlcnGOjETO_mxhI3ntsu2OIeZ8aQ291kY.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('187', '浦口区法院18法庭在我校开始建设-搜狐教育', '技术部门葛振伟工程师、校资源保障部副部长陈晓猛、实验室管理办公室主任何英、设备科科长王洪洲、法学院院长刘小冰、党委书记温晋锋、副院长张仲涛、副书记郑万秋、副院...', 'http://www.sogou.com/link?url=X4Yt6GhHd2of0mef6e3Vaq3HutfxzKETZranvFIOAF0VkUK8Am3XN2n5kfWxqC9HIeZ8aQ291kY.&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('188', '一块银色碎片促使司机自首', '2010年4月19日 - 当晚，事故中队长陈晓猛再一次复勘事故现场，在现场公路右侧排水沟内的树叶下面，又找到了一块银色碎片，正是这块银色碎片使案情初现端倪，民警断定，...', 'http://www.sogou.com/link?url=DSOYnZeCC_of1jB9gcg5jtdp24KvxQCkU2iOX4aibap5VtRvYoYhk49p6VOefgYkR2QdbJ1WaKVWfd4PoQV3mK4to0wa_Tif&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('189', '“我要把我的一切贡献给人民！”——记舍身保民的交警石健成_社会...', '2010年11月3日 - 民警陈晓猛说。     “如果时光倒流，我相信石哥还是会把生的希望留给别人。”跟随石健成工作7年多的协警刘文峰说，2003年5月，石健成带领刘文峰...', 'http://www.sogou.com/link?url=6IqLFeTuIygbfDcGkokA_QK6STFJ80mm96mAONn2CiwVh_PZIWj4hubKm6D8K7IgRYcVcbfPHwwGRSeVEFF0Nw..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('190', '加强产学研合作教育努力培养高素质创新人才_论文_百度文库', 'PDF文档 - 3页 - 113.20KB', 'http://www.sogou.com/link?url=DSOYnZeCC_owkDvmYG0gMz-JrNZwwuWKx72fSbCzb7zdqZsGrRiC8fX11nfWxo7ZIPPD8sBbqnCuLaNMGv04nw..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('191', '贵州25人死亡车祸原因查明 司机操作不当负主责-搜狐新闻', '2008年3月18日 - 组成律师团前往遵义，准备向相关部门和单位提起民事赔偿诉讼。（贵州都市报陈晓猛 唐正平） （来源：金黔在线） （责任编辑：黄芳）', 'http://www.sogou.com/link?url=6IqLFeTuIyhIw0Bsg1n_z-MN4uFqttRkTqDHsjPu6CO2WEUwWTstu2XcV-K5ENzn&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('192', '宁夏2009年全国房地产估价师执业资格考试保留成绩人员名单', '[图文]陈晓猛 908640039 贾建军 909640037 党迎泽 建设工程 教育网 档案号 姓名 档案号 姓名 档案号 姓名 档案号 姓名 640100176 白成本 907640004 陈龙908640148 孙瑾辉 客服...', 'http://www.sogou.com/link?url=DSOYnZeCC_pKZzihDKzFg2Ioibd_w6FPZvTHAtpyicl_aXrQFwhkTC7wC02KYqY_l9F2b85hcY82oVhdmeJhIIEM-8fcQ-NZcFGekRbFWryt5pUc3zy0dg..&query=%E9%99%88%E6%99%93%E7%8C%9B', '陈晓猛');
INSERT INTO `searchitem` VALUES ('193', '华南农业大学', '华南农业大学 校歌《金色的理想》 2016年招生宣传片 百年华农宣传片 2016届毕业生纪念片 全文检索： 信息发布 学生邮箱 密 码 : 校长信箱 ...', 'http://www.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('194', '华南农业大学教务处欢迎你！', '华南农业大学 首页 华南农业大学行政办公楼三楼 广州市天河区五山路483号 510642 华南农业大学教务处 版权所有 ...', 'http://jwc.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('195', '华南农业大学', '华南农业大学 校歌《金色的理想》 百年华农宣传片 全文检索： 信息发布 普通邮箱 学生邮箱 密 码 : 信息通报平台 校长信箱 校园地图 图书馆 ...', 'http://www.scau.edu.cn/scau/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('196', '华南农业大学_百度百科', '中文名 华南农业大学 英文名 South China Agricultural University 简 称 华农，华农大，SCAU 创办时间 1909年 类 别 公立大学 学校类型 综合型大学 属 性 省部共建大学 ...', 'http://baike.baidu.com/item/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('197', '华南农业大学_华南农业大学录取分数线,专业介绍 ...-新浪教育', '新浪院校库为您带来华南农业大学的详细介绍,包括:华南农业大学历史录取分数线,招生计划,重点专业,院校地址,图片,毕业生就业及薪酬等丰富信息,是考生填报志愿的最佳助手', 'http://kaoshi.edu.sina.com.cn/college/c/10564.shtml', '华南农业大学');
INSERT INTO `searchitem` VALUES ('198', '中国农业大学', '中国农业大学 版权所有 ©2017 校登记号：NW—0201 文保网安备案号:1101080025 京ICP备05004632号-1 联系我们:wlzx@cau.edu.cn ...', 'http://www.cau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('199', '华南农业大学红满堂社区|华农人！不怕苦！前途掌握在自己手 ...', '华南农业大学 红满堂社区»论坛 今日: 9280 | 昨日: 9310 | 帖子: 6387730 | 会员: 657346 | 欢迎新会员: jinde00 最新回复 论坛图片 最新帖子 最新回复 [lgd] JAVA软件工程师 ...', 'http://hometown.scau.edu.cn/bbs/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('200', '【华南农业大学图书馆】', '版权所有：华南农业大学图书馆 1999-2015(C) 中国 广州 华南农业大学图书馆 510640 电话：85280144 传真：85280144 老版主页 2014-12-29 ...', 'http://lib.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('201', '华南农业大学', '华南农业大学 校歌《金色的理想》 2016年招生宣传片 百年华农宣传片 2016届毕业生纪念片 全文检索： 信息发布 学生邮箱 密 码 : 校长信箱 ...', 'http://library.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('202', '华南农业大学研究生招生信息网', '关于由学校统筹学院未完成在职专硕研究生招生指标的说明 华南农业大学2015年在职人员攻读专业学位硕士研究生拟录 2015级在职专业学位硕士研究生二阶段考试成绩查询', 'http://web.scau.edu.cn/yjsy/yzb/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('203', '华南农业大学 - 百度百科 全球最大中文百科全书', '华南农业大学（South China Agricultural University），建立于1909年，是一所以农业科学为优势、以生命科学为特色，农、工、文、理、经、管、法、艺术七大学科全面发展 ...', 'http://baike.baidu.com/subview/21205/21205.htm', '华南农业大学');
INSERT INTO `searchitem` VALUES ('204', '华南农业大学_华南农业大学录取分数线,专业介绍 ...-新浪教育', '新浪院校库为您带来华南农业大学的详细介绍,包括:华南农业大学历史录取分数线,招生计划,重点专业,院校地址,图片,毕业生就业及薪酬等丰富信息,是考生填报志愿的最佳助手', 'http://kaoshi.edu.sina.com.cn/college/c/10564.shtml', '华南农业大学');
INSERT INTO `searchitem` VALUES ('205', '华南农业大学_百度百科', '华南农业大学。华南农业大学。建立于1909年。 是一所以农业科学为优势。以生命科学为特色。农。工。文。理。经。管。法。艺术七大学科全面发展。', 'https://wapbaike.baidu.com/item/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('206', '华南农业大学动科学院', '版权所有： 华南农业大学动物科学学院 2010-2015 地址：广州市天河五山华农大动物科学学院温氏楼 邮编：510642 邮箱：dongkeoffice@scau.edu.cn 电话: 020-85281547', 'http://dongke.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('207', '华南农业大学食品学院', '食品学院关于进一步加强学生宿舍消防安全和卫生检查的通知 2017/3/10 华南农业大学2016年食品科学与工程一级学科博士生国（境）外联合培养项目申请结果公示', 'http://xy.scau.edu.cn/spxy/new/cn/index.asp', '华南农业大学');
INSERT INTO `searchitem` VALUES ('208', '华南农业大学新闻网', '华南农业大学 校内报刊登记审批流程 关于广播台第十八届台委名单及职务任命的通告 您现在的位置：首页 > 宣传部 > 新闻网 > 新闻中心 新闻中心 2017-03-07 ...', 'http://web.scau.edu.cn/hnnydx/xcb/xcb_news/xwwxwzx/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('209', '华南农业大学红满堂社区|华农人！不怕苦！前途掌握在自己手 ...', '华南农业大学 红满堂社区»论坛 今日: 9280 | 昨日: 9310 | 帖子: 6387730 | 会员: 657346 | 欢迎新会员: jinde00 最新回复 论坛图片 最新帖子 最新回复 [lgd] JAVA软件工程师 ...', 'http://hometown.scau.edu.cn/bbs/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('210', '华南农业大学', '华南农业大学 校歌《金色的理想》 2016年招生宣传片 百年华农宣传片 2016届毕业生纪念片 全文检索： 信息发布 学生邮箱 密 码 : 校长信箱 ...', 'http://library.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('211', '华南农业大学-研究生院', '华南农业大学 研究生学位论文保存 华南农业大学优秀毕业研究生评选 华南农业大学优秀研究生学位论文 我校兽医学院硕士研究生在国际期刊《Emerging infectiou ...', 'http://yjsy.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('212', '华南农业大学', '华南农业大学 校歌《金色的理想》 2016年招生宣传片 百年华农宣传片 2016届毕业生纪念片 全文检索： 信息发布 学生邮箱 密 码 : 校长信箱 ...', 'http://www.sohu.comwww.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('213', '华南农业大学_互动百科', '华南农业大学-华南农业大学（South China Agricultural University），建立于1909年，是一所以农业科学为优势、以生命科学为特色，农、工、文、理、经、管 ...', 'http://www.baike.com/wiki/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('214', '华南农业大学-研究生院', '华南农业大学 研究生学位论文保存 华南农业大学优秀毕业研究生评选 华南农业大学优秀研究生学位论文 我校兽医学院硕士研究生在国际期刊《Emerging infectiou ...', 'http://yjsy.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('215', '华南农业大学-现代教育技术中心', '版权所有 华南农业大学现代教育技术中心 地址:广州市天河区五山路 邮编:510642 Mail:metc@scau.edu.cn 网站管理 ...', 'http://metc.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('216', '华南农业大学生命科学学院', '华南农业大学2016 年全省优秀中学生化学和生物夏令营招生简章 2016-06-24 2016年生命科学学院研究生导师岗位聘任公示 2016-06-03 生命科学学院纪念建党95周年表彰 ...', 'http://life.scau.edu.cn/index.asp', '华南农业大学');
INSERT INTO `searchitem` VALUES ('217', '华南农业大学 - 维基百科，自由的百科全书', '华南农业大学（在广东省一般简称华农 [1]，英语： South China Agricultural University，缩写： SCAU ），是中国大陆 广东 广州的一所重点公立教学研究型大学 ...', 'https://zh.wikipedia.org/zh-hans/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('218', '华南农业大学', '地址：广州市天河区五山华南农业大学 粤ICP备05008874号 备案编号：4401060500010 ...', 'http://bbs.scau.edu.cn/qmtt/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('219', '华南农业大学人事处', '华南农业大学2017年公开招聘辅导员和管理人员公告[16535] 2017-01-23 华南农业大学2017年公开招聘教学科研和其他专业技术人员公告[11117] 2017-01-23 华南 ...', 'http://hr.scau.edu.cn/rsc/news/show2.html?cid=28&id=58', '华南农业大学');
INSERT INTO `searchitem` VALUES ('220', '华南农业大学科学技术处', '华南农业大学科技处 版权所有 管理员登陆入口>> 地址：广东省广州市天河区五山路483号 华南农业大学科技处 邮编：510642 电话：020-85280071 传真：020-85281885 ...', 'http://kjc.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('221', '华南农业大学', '* 华南农业大学2017 年硕士研究生网报公告 2016-09-25 * 关于开展我校2016年广东省研究生教育创新计划项目申报工作的通知 2016-09-22 * 华南农业大学2017年接收 ...', 'http://100zb.scau.edu.cn/yxbcgbl/yjsc/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('222', '华南农业大学', '* 华南农业大学2017 年硕士研究生网报公告 2016-09-25 * 关于开展我校2016年广东省研究生教育创新计划项目申报工作的通知 2016-09-22 * 华南农业大学2017年接收 ...', 'http://100zb.scau.edu.cn/yxbcgbl/yjsc/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('223', '华南农业大学 - 必应网典', '进入青云路5.，稍向右转8：华南农业大学珠江学.行驶470米.沿从城大道行驶2,2679201.1.沿滨江一路行驶370米.04&，过左侧的从化骏业商业楼约90米后，左转进 …', 'http://www.bing.com/knows/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6?mkt=zh-cn', '华南农业大学');
INSERT INTO `searchitem` VALUES ('224', '华南农业大学_互动百科', '华南农业大学-华南农业大学（South China Agricultural University），建立于1909年，是一所以农业科学为优势、以生命科学为特色，农、工、文、理、经、管 ...', 'http://www.baike.com/wiki/%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('225', '华南农业大学国际教育学院', '华南农业大学 外国留学生学籍管理办法（暂行） 自主招生留学项目 报名系统 留学生报名系统 华南农业大学国际教育学院 官方微信 国际教育学院邮箱 ： cie@scau.edu.cn ...', 'http://cie.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('226', '林学与风景园林学院-华南农业大学', '林学院是华南农业大学最早设立的一个学院，发展历史源远流长，有百余年的历史。设有四个系，包括林学系、风景园林与城市规划系、森林资源与旅游管理系 ...', 'http://xy.scau.edu.cn/linxue/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('227', '华南师范大学', '华南师范大学（South China Normal University）始建于1933年，前身是广东省立勷勤大学师范学院。1996年进入国家“211 工程”重点建设大学行列，2015年成为广东省人民政府 ...', 'http://www.scnu.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('228', '华南农业大学吧_百度贴吧', '贴吧华南农业大学吧，有127861个吧友关注，共发布2099067条贴子。这里是华南农业大学学生自发组建的校园贴吧，这里是校友集聚地，这里可以聊人生，谈理想，发泄自己 …', 'http://tieba.baidu.com/f?kw=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6&ie=utf-8', '华南农业大学');
INSERT INTO `searchitem` VALUES ('229', '数学与信息学院官方网站', '招生信息 华南农业大学数学与信息学院2017年硕士研究生预调剂通知 2017-02-23 华南农业大学数学与信息学院2017年博士研究生复选结果公示 2017-01 ...', 'http://info.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('230', '华南农业大学珠江学院', '华南农业大学珠江学院是经国家教育部批准设立，实施本科层次教育的独立学院，是一所以培养德智体美全面发展、适应经济社会发展需要的应用型人才为目标的 ...', 'http://www.scauzhujiang.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('231', '华南农业大学-研究生院', '华南农业大学的研究生教育可以追溯到1935年，是全国最早招收农科研究生的学校。第一届农科硕士学位研究生毕业于1937年，至1949年共培养硕士学位研究生21人。', 'http://yjsy.scau.edu.cn/bcgl.asp', '华南农业大学');
INSERT INTO `searchitem` VALUES ('232', '华南农业大学国际教育学院', '华南农业大学 外国留学生学籍管理办法（暂行） 自主招生留学项目 报名系统 留学生报名系统 华南农业大学国际教育学院 官方微信 国际教育学院邮箱 ： cie@scau.edu.cn ...', 'http://cie.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('233', '华南农业大学 - 搜狗百科', '华南农业大学是全国重点大学，是广东省和农业部共建的“211工程”大学。校园占地8250多亩，校舍总建筑面积约137万平方米，初步形成“五湖四海一片林的紫荆 ...', 'http://baike.sogou.com/v158031.htm?fromTitle=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('234', '华南农业大学', '华南农业 博物馆筹建办 群体微生物研究中心 * 云图数字有声图书馆试用通知 2017-03-07 * “紫荆·耕读”校园读书节之“你选书·我买单” 2017-03-07 ...', 'http://123.scau.edu.cn/yxbcgbl/tsg/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('235', '华南农业大学吧_百度贴吧', '贴吧华南农业大学吧，有127861个吧友关注，共发布2099067条贴子。这里是华南农业大学学生自发组建的校园贴吧，这里是校友集聚地，这里可以聊人生，谈理想，发泄自己 …', 'http://tieba.baidu.com/f?kw=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6&ie=utf-8', '华南农业大学');
INSERT INTO `searchitem` VALUES ('236', '华南农业大学的微博_微博', '华南农业大学，华南农业大学官方微博。华南农业大学的微博主页、个人资料、相册,华南农业大学。新浪微博，随时随地分享身边的新鲜事儿。 ... #纪念毛泽东 ...', 'http://www.weibo.com/scau1909', '华南农业大学');
INSERT INTO `searchitem` VALUES ('237', '华南农业大学招生网 - 华南农业大学艺术类招生简章，分数 ...', '华南农业大学招生网发布华南农业大学艺术类招生简章，华南农业大学艺术类成绩查询，华南农业大学是广东省和农业部共建“211工程”重点大学，是全国本科 ...', 'http://www.ms315.com/school/scau.htm', '华南农业大学');
INSERT INTO `searchitem` VALUES ('238', '华南农业大学_百度知道', '华南农业大学这个，确实不好说。我就说说广东省的吧。都说华农是二本生源，真是这样麽。首先，华农招生很多，本科新生每年要1万。远超其他学校啊，这也 ...', 'https://zhidao.baidu.com/question/428792485.html', '华南农业大学');
INSERT INTO `searchitem` VALUES ('239', '华南农业大学珠江学院', '华南农业大学珠江学院是经国家教育部批准设立，实施本科层次教育的独立学院，是一所以培养德智体美全面发展、适应经济社会发展需要的应用型人才为目标的 ...', 'http://www.scauzhujiang.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('240', '资源环境学院院网--华南农业大学', '华南农业大学资源环境学院官方网站 ... 中英环境科学研究中心（国际联合实验室）签约和揭牌仪式在我校举行', 'http://zyhjxy.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('241', '华南农业大学实验动物中心- 首页', '华南农业大学 实验动物中心 首页 中心概况 新闻公告 技术服务 教学科研 申请实验 资料下载 联系我们 预约 中心图片 中心简介 硬件设施 中心资质 中心新闻 [2016 ...', 'http://sydwzx.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('242', '华南农业大学', '今年将加码海外研发中心建设03-09 ·【中国诗歌网】广州诗友在华南农业大学举行紫荆花诗会03-08 ·【金羊网】聚焦广东团开放日 多听听来自基层的声音03-07 ·【中国经济网】凝心聚力 攻坚克难（节选）03-07 更多... · [要闻] 华农3人入选...', 'http://www.scau.edu.cn/', '华南农业大学');
INSERT INTO `searchitem` VALUES ('243', '华南农业大学_高考分数线_高考派', '该校在当前条件下暂无分数线数据！', 'http://www.gaokaopai.com/daxue-luquxian-575.html', '华南农业大学');
INSERT INTO `searchitem` VALUES ('244', '华南农业大学_招生信息_中国教育在线', '研究生院', 'http://gkcx.eol.cn/schoolhtm/schoolTemple/school287.htm?furl=sogou', '华南农业大学');
INSERT INTO `searchitem` VALUES ('245', '华南农业大学教务处欢迎你！', '中南民族大学来我处调研教育信息化和教学管理工作 教务处新学期工作会强调：增强服务意识 狠抓工作落实 学校召开新学期本科教学工作会 学校检查新学期教学准备工作 教务处...', 'http://www.sogou.com/link?url=CrexC2hj5_5Qpi-YY-jg_j4IRDdG1RpI&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('246', '华南农业大学高考招生——高考志愿填报参考系统', '权威发布华南农业大学2016年高考招生信息查询，内容包括2016年高考招生计划和招生简章查询、各省及高校历年录取分数线查询、分专业录取分数线查询，并提供2016年高考招...', 'http://www.sogou.com/link?url=MRoBrhLn5VMlXr5ogt11x22jKhG7F5hMkB-3bgBiAC80w8ulCBuAVNvgFuc2FWRdcmvoHJ8vZPk.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('247', '华南农业大学就业信息网', '华南农业大学招生就业云服务平台 云就业 高校 大学 大学生 就业 就业网 就业信息网 就业指导 就业指导中心 就业中心 创业 创业指导', 'http://www.sogou.com/link?url=CrexC2hj5_40L9WgSuG3ozxXaFiPJee7reaVHN88tHY.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('248', '华南农业大学_搜狗知识（全部约13074条结果）', '2012-06-306个回答华南农业大学怎么样 - 搜狗问问', 'http://www.sogou.com/link?url=lf8qxtL2NiS2wpt7ulLAcw-VjbWECLE32dXtMX2WXDUGr1CXzNT5cM2Rke3dXO-FBYQWYbgzScrB81gzhbreTve5LYd6_lqH69wLOzuJ7ee4Me04MWNNOJg4pnQPAxCYPZsl-bJDKJ2NggIcAvvXLljc78yvvL6JcdBVI97rYUw.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('249', '在华南农业大学(scau)就读是怎样一番体验?_知乎', '85(虽然禁养,还是耐不住兽医学院的养动物习惯)5、日常活动多,简称华南活动大学,但精品活动略少.6、校区交通很方便,广州地铁三号线五山站,公交:b10,78,...更多>>', 'http://www.sogou.com/link?url=hedJjaC291MBtMZVirtXo7CqjI0tE6P9WJaAWBJP7DW5n25jdWSqSUWhenQX32SNjm5O7vCRJBg.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('250', '华南农业大学珠江学院—华南农业大学珠江学院', '华南农业大学珠江学院是经国家教育部批准设立，实施本科层次教育的独立学院，是一所以培养德智体美全面发展、适应经济社会发展需要的应用型人才为目标的普通高等学校。...', 'http://www.sogou.com/link?url=DSOYnZeCC_qMs5Sv8_8PIzVBabxeoQ2cB30X9Rx_BO4.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('251', '华南农业大学-搜狐教育高校信息库-高校、专业一站查询', '华南农业大学是广东省和农业部“九五”、“十五”共建“211工程”全国重点大学，已有98年的办学历史。校园坐落在素有“花城”美誉的广州市区，占地8250多亩，校舍总建...', 'http://www.sogou.com/link?url=WaeIF24cBDuAsx35xEeJRD21_Kw5wgrdNChSREaLtIUk8wz7xpWrLPg6CKAK0IS4&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('252', '华中农业大学教务处-华农教务处', '华中农业大学教务处开设的网站，可以来这里查询相关教学信息。 李忠云考察劲牌公司并... 素质教育是教育改革发... 2015年教育思想大讨论... “千问计划”——开启... 华中农业大学...', 'http://www.sogou.com/link?url=CrexC2hj5_51dzd8ZO1PEj4IRDdG1RpI&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('253', '华南农业大学贴吧首页__一点网SCAU校园网站主页 华农', '华南师范大学增城学院贴吧 广州民航职业技术学院贴吧 华南理工大学广州汽车学院贴吧 广东商学院华商学院贴吧 香港浸会大学联合国际学院贴吧 广东省国防工业职工大学贴吧 河...', 'http://www.sogou.com/link?url=DSOYnZeCC_pfjfIM3xSKAtui4JMbXxrd&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('254', '华南农业大学工程学院 - 首页', '华南农业大学工程学院 English Version 陈晓阳校长为我院师生讲授新学期第一堂思政课 我院在VEX机器人亚洲公开赛斩获佳绩 工程学院举行共青团融入“大思政”战略学习分享会...', 'http://www.sogou.com/link?url=MRoBrhLn5VNY0K91kagWZzxXaFiPJee7reaVHN88tHY.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('255', '华南农业大学自考网_是官网指定唯一华南农业大学自考专业_报名地点', '华南农业大学自考网为大众提供华南农业大学自考报名时间查询，华南农业大学自考全日制专业以及华农新闻等最新资讯，自考报名电话400-000-2300', 'http://www.sogou.com/link?url=NdaMVEDuTuVo7w4vJeuXyCED4QniNDJ4reaVHN88tHY.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('256', '华南农业大学研究生院_华南农业大学研究生招生信息网_华南农业大学...', '[图文]华南农业大学考研网，提供华南农业大学考研招生信息、大纲解析、资料下载、成绩查询、复试分数线、考研调剂等信息，华南农业大学考研从考研网（kaoyan.com）开始。...', 'http://www.sogou.com/link?url=TdXYaTdl0k7Xxt6XzORKaqNNKTuOwMgF0Ha3cgDN3tA.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('257', '欢迎光临 - 专本连读招生办公室 - 华南农业大学', '华南农业大学自考招生网提供华南农业大学自考专科，专本连读，华农自考本科招生最新信息，是广东2015年华南农业大学自考招生信息指定报名网.招生电话：020-85282013', 'http://www.sogou.com/link?url=DSOYnZeCC_reSZZSRAgHdXITgI_gWqj4mE_OPEmgRcCt5pUc3zy0dg..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('258', '华南农业大学自考招生网-华南农业大学自学考试|广州市华南农业大学...', '华南农业大学自考招生是专门为华南农业大学自学考试考生提供报名咨询与考试服务的专业性网站。是广州市成科教育培训中心招生办公室发布招生考试信息的重要途径，主要为各...', 'http://www.sogou.com/link?url=NdaMVEDuTuUBu0PTvXwKVGcR16PK93Pz&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('259', '华南农业大学研究生招生信息-中国教育在线研究生招生报名查询系统', '[图文]华南农业大学2015年研究生招生信息，包括华南农业大学2015年研究生招生简章、专业目录、参考书目、考研分数线、考研复试、招生计划、招录比例等硕士博士研究生招生...', 'http://www.sogou.com/link?url=LeoKdSZoUyAT2gIyYmpSMYlsWhHv1MJO3rZgSWhYt4Qef9Ls5VRRjrbAp6VRqT6Q&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('260', '华南农业大学', '[图文]本次学术活动获得华南农业大学“海外名师讲座计划”资助，也是我校承办的广东省研究生论坛植物学分论坛学术活动内容之一。（文/图 生命科学院 赵秀彩） （责任编辑：蒙...', 'http://www.sogou.com/link?url=DSOYnZeCC_pfjfIM3xSKAlVGrXJD_kKhslXwdclU7eMDZwF9l3JsDoqfHdun9TiOnG4bmeiRpUU.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('261', '华南农业大学_互动百科', '[图文]华南农业大学-华南农业大学（South China Agricultural University），建立于1909年，是一所以农业科学为优势、以生命科学为特色，农、工、文、理、经、管、法、艺术多学...', 'http://www.sogou.com/link?url=DSOYnZeCC_pZDwVe35a9NWX4NDqByCW_QltDNLwbBboi7j4VyScxL1jvA1pT1y2WCzsdcTBfNP9g04YjBkZb9WDlBXqpqgUT2yznRDDrjK6t5pUc3zy0dg..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('262', '华南农业大学红满堂 - 搜狗百科', '红满堂是华南农业大学的历史文化符号、标志性建筑。全国首个砖拱建筑，被称为“广东壳”的红满堂，建于1958年大跃进时期。在当时技术革新浪潮下，华南理工大学...', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgfRQftDTmAlv26FDhCNBXEMyyUtg79KV3X9cHLzs91CcGr1CXzNT5cO0mwmlbk1k3VAHnx2ej4BIdddnKIBijw27h8DcLg7Dq&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('263', '在华南农业大学(scau)就读是怎样一番体验?_知乎', '85(虽然禁养,还是耐不住兽医学院的养动物习惯)5、日常活动多,简称华南活动大学,但精品活动略少.6、校区交通很方便,广州地铁三号线五山站,公交:b10,78,...更多>>', 'http://www.sogou.com/link?url=hedJjaC291MBtMZVirtXo7CqjI0tE6P9WJaAWBJP7DW5n25jdWSqSUWhenQX32SNjm5O7vCRJBg.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('264', '华南农业大学2014年人才招聘启事 - 教师招聘|高校教师招聘|特聘教授...', '[图文]免责声明： ①凡本站注明“稿件来源：中国教育在线”的所有文字、图片和音视频稿件，版权均属本网所有，任何媒体、网站或个人未经本网协议授权不得转载、链接、转贴或...', 'http://www.sogou.com/link?url=DSOYnZeCC_pvhTUBJL786VeX8mgZuOXH46b2KExLbl0FJn0U3ucPVt_do-D9tVaM0JgTN822iZhl3FfiuRDc5w..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('265', '【华南农业大学图书馆】', '华南农业大学图书馆自2007年开始从事科技查新工作，2010年12月被教育部认定为农学类＂教育部科技查新工作站＂（序号N09）。 几年来华南农业大学科技查新工作站共完成国...', 'http://www.sogou.com/link?url=X4Yt6GhHd2oMUrZqGImuM_NWzIvvZmwwJVcE6Z9sdQMif0koYmv1Ha3mlRzfPLR2&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('266', '华南农业大学全面放开双学位_新浪教育_新浪网', '[图文]华南农业大学招办曾雅丽主任做客新浪 新浪教育[微博]讯2012年高考[微博]即将拉开大幕，高校招生有哪些新政策？2012各高校招生计划、招生政策有何变化？为帮助考生了解...', 'http://www.sogou.com/link?url=B7ss7T7Ay4mBcE-CAy3RX3VSEY1AZdrl5m1l-aGJ_X5bXePL6WOVZz__YDZW5h5cYS5PY09Dqv-uLaNMGv04nw..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('267', '华南农业大学怎么样？ - 搜狗问问', '6个答案 - 提问时间: 2017-02-28 - 5个赞', 'http://www.sogou.com/link?url=DSOYnZeCC_rZXVZCtvPXjmRFzFBIhMTsk7tu_YqSP8knYVrXtXw5wa3mlRzfPLR2&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('268', '华南农业大学研究生处', '华南农业大学的研究生教育可以追溯到1937年，是全国最早招收农科研究生的学校。第一届农科硕士学位研究生毕业于1937年，至1949年共培养硕士学位研究生21人。解放后1953...', 'http://www.sogou.com/link?url=DSOYnZeCC_rp1qY_Makw91YfFavf4aFozE2I65db6cit5pUc3zy0dg..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('269', '华南农业大学兽医学院 - 搜狗百科', '华南农业大学兽医学院历史悠久，1952年由原中山大学、岭南大学、广西大学的畜牧兽医系合并成立为华南农学院畜牧兽医系，首任系主任为中国著名兽医学家邝荣禄教...', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgDw86hxklsdxVy6JvJfJZBvCJC-1zdrX61yfjWXgGbs8u1HGAqrzRozRoyqUcAN0UsnvA1ohcR3o_9siIG0w_Om2y4efutfu7RCjOZAH_2Ra83WUMjc7q7-NA_3DDCsbE&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('270', '华南农业大学经济类研究生怎么样？ - 搜狗问问', '1个答案 - 提问时间: 2009-05-26 - 68个赞', 'http://www.sogou.com/link?url=DSOYnZeCC_rZXVZCtvPXjmRFzFBIhMTs-Y2oG0VyB-3X2aqhUc2TQ8_fE_qQkO2P&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('271', '华南农业大学学报 - 搜狗百科', '《华南农业大学学报》社会科学版创刊于2002年，为国内外公开出版发行的社科类综合性中文核心期刊，主要刊登经济管理、文史哲类人文社科领域的研究性学术论文。现为季刊，每期156页。现为CSSCI（扩展版）来源期刊，RCCSE中国核心学术期刊（A），全国百强社科期刊。', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgYWYNJCVcN9FVy6JvJfJZBvCJC-1zdrX61yfjWXgGbs8u1HGAqrzRozRoyqUcAN0UI0DvzZXMFuQfO3epigim8CLVZ6dF_vKLU9INHxfQfiK83WUMjc7q797hWsll8Ly6&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('272', '华南农业大学研究生院 - 搜狗百科', '华南农业大学的研究生教育可以追溯到1935年，是全国最早招收农科研究生的学校。第一届农科硕士学位研究生毕业于1937年，至1949年共培养硕士学位研究生21人。...', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgNCMXTVRSDe5Vy6JvJfJZBvCJC-1zdrX61yfjWXgGbs8u1HGAqrzRozRoyqUcAN0UI0DvzZXMFuQfO3epigim8CLVZ6dF_vKLfoUfXqXHN3ZCM50unBFETUzZZg5HQXrYD4vFnqzMTvDypzrYzixIQ47ig65r5gTY&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('273', '华南农业大学红满堂二手市场', '华南农业大学红满堂二手市场 | 广州地区最受欢迎的大学生二手市场 感受华农，感受生活！我们就是华农人！', 'http://www.sogou.com/link?url=58p16RfDRLtk0Lfrv7VGskSoxaTzYuo2xcLO2TQn7Ac.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('274', '华南农业大学经济类研究生怎么样？_百度知道', '1个答案 - 提问时间: 2009-05-30 - 55个赞', 'http://www.sogou.com/link?url=44aejrzSKwXnIIljYInpjGXH0kc1pIdiSq3aTswAtP0kuYkDa3H4TiXw5Pqtik-2&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('275', '华南农业大学怎么样？_百度知道', '4个答案 - 提问时间: 2011-07-12 - 19个赞', 'http://www.sogou.com/link?url=44aejrzSKwXnIIljYInpjGXH0kc1pIdiSq3aTswAtP1tyQkPtbQvTcOyCgYovbtB&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('276', '华南农业大学 电话,地址,图片,营业时间-广州-大众点评网', '[图文]华南农业大学。进入华南农业大学页面，查看更多关于华南农业大学的地址、电话、价格、营业时间介绍，了解华南农业大学最新的折扣优惠信息、用户点评信息。', 'http://www.sogou.com/link?url=DSOYnZeCC_qQGjKhAW_Va0vPKcw8JICxHgGsm0IiLe8Fh-jSLEWxJQ..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('277', '华南农业大学自考招生网-华南农业大学自考报名,华农自考专业,华...', '华南农业大学是全国重点大学，是广东省和农业部共建的“211工程”大学。校园坐落在素有“花城”美誉的广州市，占地8250多亩，校舍总建筑面积约137万平方米，初步形成“...', 'http://www.sogou.com/link?url=DSOYnZeCC_qMs5Sv8_8PI5nvC8KPpJ6x&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('278', '华南农业大学_百度文库', 'TXT文档 - 14页 - 28.92KB', 'http://www.sogou.com/link?url=DSOYnZeCC_owkDvmYG0gMz-JrNZwwuWKb1xZle9QWVH3gPM5bRNU_YHb_5Yq0_mBsoC9gfANe82uLaNMGv04nw..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('279', '华南农业大学首页_中国高校信息查询系统_腾讯高考频道', '其它农业类院校 其它广东院校 嘉应学院 华南师范大学 华南理工大学广州学院 惠州学院 韩山师范学院 广东海洋大学 广东工业大学 广东医学院 广东药学院 广东外语外贸大学 广东石...', 'http://www.sogou.com/link?url=WaeIF24cBDvrjmRICeTjHCLwDjNU13cVDccWtFxM98WvV9HuMAPbSe4KsnPaM30ltsCnpVGpPpA.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('280', '华南农业大学生命科学学院', '管理登录 | 首页 | 相关链接： 地址：广州市天河区五山路483号华南农业大学生命科学学院 邮编：510642 电话：020-85280185 传真：020-85282180', 'http://www.sogou.com/link?url=X4Yt6GhHd2pVXcz8u5QA_zxXaFiPJee7reaVHN88tHY.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('281', '华南农业大学考研论坛_华南农业大学考研网_考研论坛（kaoyan.com）', '华南农业大学考研论坛，让报考华南农业大学的研友们轻松抱团，一起分享华南农业大学考研信息、考研经验和真题笔记资料，从此告别孤独与寂寞，你懂的！', 'http://www.sogou.com/link?url=DOb0bgH2eKi_j8OUICH73SgcyN5oVbSoNz30Z_xg6y0.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('282', '华南农业大学视频网', '[图文]华南农业大学2016年招生宣传片《我的大学… 华南农业大学2016届毕业纪念片《骊歌》 华南农业大学“紫荆校园”官方宣传片 华南农业大学2016年新春贺岁视频 华南农业大...', 'http://www.sogou.com/link?url=DSOYnZeCC_rp1qY_Makw94RY3rIwBgMJnjfUg2aufDuWgfWR3uS4uuMxULEjs9lWPA49myxJbtPeZjmx8vU6UQ..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('283', '华南农业大学——高清地图_百度文库', 'Word文档 - 1页 - 872.62KB', 'http://www.sogou.com/link?url=DSOYnZeCC_owkDvmYG0gMz-JrNZwwuWKthxnL6Tg-TBHZFiiQ5BpGo4A8z0hI32pWXJUsrIPEkOuLaNMGv04nw..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('284', '华南农业大学经济管理学院 - 搜狗百科', '华南农业大学经济管理学院由国立中山大学农学院与私立岭南大学农学院的农业经济教育专业发展而来。1952年全国院系调整，建立华南农学院农业经济教研室。“文革...', 'http://www.sogou.com/link?url=DOb0bgH2eKjRiy6S-EyBciCDFRTZxEJgj_tg6atLQ3ZVy6JvJfJZBvCJC-1zdrX61yfjWXgGbs8JyGpmoQaT_Z8ThGbnsfg-e_R80MowWwqejkjnGnxSyg..&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('285', '2016年华南农业大学考研调剂汇总_华南农业大学考研调剂_考研帮（...', '2016年考研复试分数线即将陆续公布，很多考生面临考研调剂，为方便各位考生搜集信息，考研帮特将华南农业大学2016年考研调剂信息进行了汇总，希望对大家有一定帮助。请...', 'http://www.sogou.com/link?url=TdXYaTdl0k7Xxt6XzORKaqNNKTuOwMgFrTkjjsXcSVndHT1OBg2M14EpDVwGa8VwtsCnpVGpPpA.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('286', '华南农业大学', '[图文] 为把脱贫攻坚工作做细做实，东源县法院充分发挥高等农业院校的智库作用，善于借助“外脑”，切实提高精准扶贫工作质量。 日前，在华南农业大学党委统战部的支持下，...', 'http://www.sogou.com/link?url=DSOYnZeCC_pfjfIM3xSKAsrMma4td9NNiuXdD_rSXl1VCXVBHo2xvuJcH1aSbg0tCPB73DLf9Vc.&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
INSERT INTO `searchitem` VALUES ('287', '华南农业大学2017年人才招聘启事 - 教师招聘|高校教师招聘|特聘教授...', '[图文]华南农业大学人才招聘移动平台二维码： 华南农业大学“紫荆”国际青年学者论坛 一、举办目的 为进一步推动学校高水平建设发展战略和学科建设需要，不断提高引进人才的...', 'http://www.sogou.com/link?url=DSOYnZeCC_pvhTUBJL786Rj9KhgfmwMFooc4gqQmwhP0WXYm-FJZpJe3yW9nnh4mUqwD2doBKVb6j1K1mzxEllrhHGZYy7mLjIeQLiVWNr4K9dvvbnhR463mlRzfPLR2&query=%E5%8D%8E%E5%8D%97%E5%86%9C%E4%B8%9A%E5%A4%A7%E5%AD%A6', '华南农业大学');
